## Q-1) MegaCity Builders is a construction company. They seek the help of their data analyst to generate employee codes from 1 to 1,000 for their part time work force, as they are not interested in RDBMS solution.

In [1]:
import numpy as np
empid = np.arange(1,1001) # The arange function returns an array of integers starting from 1 to 1000 
print(empid)

[   1    2    3    4    5    6    7    8    9   10   11   12   13   14
   15   16   17   18   19   20   21   22   23   24   25   26   27   28
   29   30   31   32   33   34   35   36   37   38   39   40   41   42
   43   44   45   46   47   48   49   50   51   52   53   54   55   56
   57   58   59   60   61   62   63   64   65   66   67   68   69   70
   71   72   73   74   75   76   77   78   79   80   81   82   83   84
   85   86   87   88   89   90   91   92   93   94   95   96   97   98
   99  100  101  102  103  104  105  106  107  108  109  110  111  112
  113  114  115  116  117  118  119  120  121  122  123  124  125  126
  127  128  129  130  131  132  133  134  135  136  137  138  139  140
  141  142  143  144  145  146  147  148  149  150  151  152  153  154
  155  156  157  158  159  160  161  162  163  164  165  166  167  168
  169  170  171  172  173  174  175  176  177  178  179  180  181  182
  183  184  185  186  187  188  189  190  191  192  193  194  195  196
  197 

# Q-2) 
## The company decides to give cash bonus to its employees on Christmas.  How can you generate the random bonus amounts ranging from 100 USD to 300 USD for the 1,000 employees?


In [2]:
bonus = np.random.randint(100,300,1000)
print(bonus)

[132 284 292 133 135 290 215 180 182 157 279 261 296 238 136 244 164 299
 291 143 285 102 161 135 195 100 216 224 280 142 265 147 232 288 190 127
 267 271 151 130 228 239 175 298 161 261 286 101 100 124 207 260 105 274
 195 110 200 221 290 174 278 201 153 229 180 102 108 102 112 139 262 115
 182 171 180 238 204 289 284 129 203 171 239 114 212 254 271 104 118 219
 181 123 265 162 260 230 225 230 280 177 204 209 286 119 272 112 115 226
 180 228 189 164 222 210 112 275 167 192 227 230 208 161 256 158 152 173
 267 182 175 253 284 191 244 196 213 198 237 115 182 100 145 118 171 110
 209 198 227 174 226 280 297 108 121 121 176 241 209 154 162 184 139 154
 257 247 187 284 210 254 227 197 106 222 108 248 229 182 178 172 115 146
 161 246 187 257 286 263 141 146 233 146 264 262 190 121 129 248 130 273
 197 248 281 193 113 164 241 129 241 154 235 170 279 158 234 255 263 172
 259 171 250 249 200 194 143 232 176 174 196 131 132 175 231 250 211 207
 179 289 158 187 147 192 139 279 264 108 113 244 17

# Q-3) 
## MegaCity builders has a total of 1,000 part-time employees. The annual salary of these employees lies between 10,000 USD to 20,000 USD. The company wishes to find the average annual salary of employees. 

In [3]:

#Let's first generate the salaries in between 10,000 USD to 20,000USD 
#for 1000 employees and then find the average salary using this data


sal = np.random.randint(10000,20000,1000)
print(sal) # Checking how the salary data looks like..


[16610 11432 17993 10712 16787 12940 13328 16097 11988 14433 13582 15349
 14590 16172 12512 11524 19291 18185 13564 12193 13250 18415 17969 13620
 18559 14367 14831 14625 14754 19205 12138 13277 19274 17984 13417 16875
 13486 12655 10233 14751 14005 11446 13203 17281 15062 16600 15234 13255
 14938 16375 13000 10547 14937 14316 16784 17355 19587 14345 18855 11045
 15581 16785 11877 16603 10147 14034 19488 19086 15832 16974 11439 13317
 15662 14983 15880 11261 15175 15367 12245 15110 13441 18124 14592 19234
 14670 19403 10304 11884 10998 17349 12045 17786 11348 12839 17458 14296
 17705 10758 13614 14790 13075 11863 16505 13839 12112 15344 18616 15708
 12689 11303 19977 13584 14793 18661 15486 11324 10149 17434 19951 15815
 11206 19782 10572 13653 19233 18894 13803 19961 13405 16550 18938 16612
 17827 10574 18089 13564 11757 19110 16706 17435 16166 14491 15089 15239
 15995 15583 12010 11089 15211 16021 16141 10942 12505 13506 18123 19355
 17553 18807 11728 19861 18198 13435 17109 17213 13

In [4]:
#Finding average salary
avgsal = np.mean(sal)
print("The average annual salary of employees: ", avgsal)

The average annual salary of employees:  15062.407


# Q-4) Print the salaries of all the employees with the bonuses included.


In [5]:
newctc = sal+bonus # Numpy arrays allows 2 equal size array elements to be added , element by element 
newctc


array([16742, 11716, 18285, 10845, 16922, 13230, 13543, 16277, 12170,
       14590, 13861, 15610, 14886, 16410, 12648, 11768, 19455, 18484,
       13855, 12336, 13535, 18517, 18130, 13755, 18754, 14467, 15047,
       14849, 15034, 19347, 12403, 13424, 19506, 18272, 13607, 17002,
       13753, 12926, 10384, 14881, 14233, 11685, 13378, 17579, 15223,
       16861, 15520, 13356, 15038, 16499, 13207, 10807, 15042, 14590,
       16979, 17465, 19787, 14566, 19145, 11219, 15859, 16986, 12030,
       16832, 10327, 14136, 19596, 19188, 15944, 17113, 11701, 13432,
       15844, 15154, 16060, 11499, 15379, 15656, 12529, 15239, 13644,
       18295, 14831, 19348, 14882, 19657, 10575, 11988, 11116, 17568,
       12226, 17909, 11613, 13001, 17718, 14526, 17930, 10988, 13894,
       14967, 13279, 12072, 16791, 13958, 12384, 15456, 18731, 15934,
       12869, 11531, 20166, 13748, 15015, 18871, 15598, 11599, 10316,
       17626, 20178, 16045, 11414, 19943, 10828, 13811, 19385, 19067,
       14070, 20143,

# Q-5) 
## The HR of MegaCity Builders wishes to print those employee id's that are even numbers.

In [6]:
empid = np.arange(1,1001) # The object "e,pid" contains the employee codes from 1 to 1000
empid[1::2]
# One could also use  empid[1:1001:2]

array([   2,    4,    6,    8,   10,   12,   14,   16,   18,   20,   22,
         24,   26,   28,   30,   32,   34,   36,   38,   40,   42,   44,
         46,   48,   50,   52,   54,   56,   58,   60,   62,   64,   66,
         68,   70,   72,   74,   76,   78,   80,   82,   84,   86,   88,
         90,   92,   94,   96,   98,  100,  102,  104,  106,  108,  110,
        112,  114,  116,  118,  120,  122,  124,  126,  128,  130,  132,
        134,  136,  138,  140,  142,  144,  146,  148,  150,  152,  154,
        156,  158,  160,  162,  164,  166,  168,  170,  172,  174,  176,
        178,  180,  182,  184,  186,  188,  190,  192,  194,  196,  198,
        200,  202,  204,  206,  208,  210,  212,  214,  216,  218,  220,
        222,  224,  226,  228,  230,  232,  234,  236,  238,  240,  242,
        244,  246,  248,  250,  252,  254,  256,  258,  260,  262,  264,
        266,  268,  270,  272,  274,  276,  278,  280,  282,  284,  286,
        288,  290,  292,  294,  296,  298,  300,  3

# Q-6) 
##  The company wishes to provide extra bonus of 200 USD to all the employees.  How can you add 200 USD to each employee's bonus?

In [7]:
#print(b) # Already existing set of bonus details for 1000 employees 
updatedbonus = np.add(bonus,200)
updatedbonus

array([332, 484, 492, 333, 335, 490, 415, 380, 382, 357, 479, 461, 496,
       438, 336, 444, 364, 499, 491, 343, 485, 302, 361, 335, 395, 300,
       416, 424, 480, 342, 465, 347, 432, 488, 390, 327, 467, 471, 351,
       330, 428, 439, 375, 498, 361, 461, 486, 301, 300, 324, 407, 460,
       305, 474, 395, 310, 400, 421, 490, 374, 478, 401, 353, 429, 380,
       302, 308, 302, 312, 339, 462, 315, 382, 371, 380, 438, 404, 489,
       484, 329, 403, 371, 439, 314, 412, 454, 471, 304, 318, 419, 381,
       323, 465, 362, 460, 430, 425, 430, 480, 377, 404, 409, 486, 319,
       472, 312, 315, 426, 380, 428, 389, 364, 422, 410, 312, 475, 367,
       392, 427, 430, 408, 361, 456, 358, 352, 373, 467, 382, 375, 453,
       484, 391, 444, 396, 413, 398, 437, 315, 382, 300, 345, 318, 371,
       310, 409, 398, 427, 374, 426, 480, 497, 308, 321, 321, 376, 441,
       409, 354, 362, 384, 339, 354, 457, 447, 387, 484, 410, 454, 427,
       397, 306, 422, 308, 448, 429, 382, 378, 372, 315, 346, 36

# Q-7) 
## The HR wishes to know how many employees are getting salaries more than 15,000 USD per year. 


In [8]:
sal.size # The size tells us the number of data items in the array "sal"

1000

In [9]:
index = np.where(sal > 15000)
#print(index)
# index contains the positions of the array "sal" where salary > 15000 is satisfied
print(sal[index]) 
#Here the output represents all the salaries more than 15000 USD
#The next step is to find the total number of employees whose salary is greater than 15000

[16610 17993 16787 16097 15349 16172 19291 18185 18415 17969 18559 19205
 19274 17984 16875 17281 15062 16600 15234 16375 16784 17355 19587 18855
 15581 16785 16603 19488 19086 15832 16974 15662 15880 15175 15367 15110
 18124 19234 19403 17349 17786 17458 17705 16505 15344 18616 15708 19977
 18661 15486 17434 19951 15815 19782 19233 18894 19961 16550 18938 16612
 17827 18089 19110 16706 17435 16166 15089 15239 15995 15583 15211 16021
 16141 18123 19355 17553 18807 19861 18198 17109 17213 19805 18371 15485
 19787 16928 17680 16931 17782 15826 15240 19998 17115 18761 17100 16512
 17993 17226 18144 15050 18906 15165 16458 17837 15989 18344 16713 18848
 17152 19141 16368 15713 18737 17722 19895 19507 18402 19437 17739 16930
 18431 18452 19187 15221 17775 17384 17371 17768 15218 18739 15258 18770
 15322 18261 16340 18507 15375 17344 19385 16032 15190 19718 19370 15841
 19580 15467 15215 19327 16192 17183 19120 17029 19693 17296 18895 18396
 17041 15042 17100 16309 17060 17341 17647 19685 16

In [10]:
print("Total number of emplyees who's salary is more than $7500 is:", np.size(index) )

Total number of emplyees who's salary is more than $7500 is: 517


# Q-8) 
## The employees with the codes 5, 124, 200, 332, 420, 589, 665, 743, 887, and 901 like to resign. As per the policy, the company does not save the data of part-time employees once they have resigned.  How can you delete these record/data of employees? Consider the array "dup" to contain a copy of the employee codes.


In [11]:
dup = empid.copy() # We are cloning a copy to demonstrate deletion of data
dup

array([   1,    2,    3,    4,    5,    6,    7,    8,    9,   10,   11,
         12,   13,   14,   15,   16,   17,   18,   19,   20,   21,   22,
         23,   24,   25,   26,   27,   28,   29,   30,   31,   32,   33,
         34,   35,   36,   37,   38,   39,   40,   41,   42,   43,   44,
         45,   46,   47,   48,   49,   50,   51,   52,   53,   54,   55,
         56,   57,   58,   59,   60,   61,   62,   63,   64,   65,   66,
         67,   68,   69,   70,   71,   72,   73,   74,   75,   76,   77,
         78,   79,   80,   81,   82,   83,   84,   85,   86,   87,   88,
         89,   90,   91,   92,   93,   94,   95,   96,   97,   98,   99,
        100,  101,  102,  103,  104,  105,  106,  107,  108,  109,  110,
        111,  112,  113,  114,  115,  116,  117,  118,  119,  120,  121,
        122,  123,  124,  125,  126,  127,  128,  129,  130,  131,  132,
        133,  134,  135,  136,  137,  138,  139,  140,  141,  142,  143,
        144,  145,  146,  147,  148,  149,  150,  1

In [12]:

new_dup = np.delete(dup, (5-1, 124-1, 200-1, 332-1, 420-1, 589-1, 665-1, 743-1, 887-1,901-1), axis=0)
new_dup

array([   1,    2,    3,    4,    6,    7,    8,    9,   10,   11,   12,
         13,   14,   15,   16,   17,   18,   19,   20,   21,   22,   23,
         24,   25,   26,   27,   28,   29,   30,   31,   32,   33,   34,
         35,   36,   37,   38,   39,   40,   41,   42,   43,   44,   45,
         46,   47,   48,   49,   50,   51,   52,   53,   54,   55,   56,
         57,   58,   59,   60,   61,   62,   63,   64,   65,   66,   67,
         68,   69,   70,   71,   72,   73,   74,   75,   76,   77,   78,
         79,   80,   81,   82,   83,   84,   85,   86,   87,   88,   89,
         90,   91,   92,   93,   94,   95,   96,   97,   98,   99,  100,
        101,  102,  103,  104,  105,  106,  107,  108,  109,  110,  111,
        112,  113,  114,  115,  116,  117,  118,  119,  120,  121,  122,
        123,  125,  126,  127,  128,  129,  130,  131,  132,  133,  134,
        135,  136,  137,  138,  139,  140,  141,  142,  143,  144,  145,
        146,  147,  148,  149,  150,  151,  152,  1

# Q 9 ) How will you check if the employee with the employee id 5 is actually deleted or not? This has to be done without printing the whole array.


In [13]:
# Lets check if the element 5 is actually deleted from the array "new_dup"
5 in new_dup # This line of code would check if the data 5 is present in array "d"


False

# Question 10
# The array "new_dup" now has the employee IDs, after deleting a few employee ID's. Delete the employees the with employee codes 101 and 201.


In [14]:
# Lets find the index locations of data items 101 and 201, and then delete 
pos101 = np.where(new_dup == 101)
pos201 = np.where(new_dup == 201)
print(pos101,pos201)
# Complete the code to perform the delete operation 

(array([99], dtype=int64),) (array([197], dtype=int64),)


# Q-11) 
## The HR wants to hire 10 new employees, assign them the employee codes from 1001 to 1010, and add the data in the existing employee codes. How can you accomplish this task? Consider the array "empid" which originally contains the employee ID's. 


In [15]:
newid = np.arange(1001,1011) # Lets generate the new set of employee ID's
print(newid)

[1001 1002 1003 1004 1005 1006 1007 1008 1009 1010]


In [16]:
empid=np.append(empid,newid) # We are appending the new employee ID's to the original array "empid"
print(empid)

[   1    2    3 ... 1008 1009 1010]


# Q-12) 
## The company wants to know the top 10 highest salaries of employees. Display it. The array 'sal' contains the salaries of all employees.


In [17]:
#Getting the values in ascending order
np.sort(sal) # The salary of the employees are in the range of 10000 to 20000 USD p.a 

array([10028, 10046, 10064, 10067, 10103, 10110, 10125, 10132, 10136,
       10147, 10149, 10168, 10174, 10184, 10185, 10189, 10203, 10209,
       10214, 10233, 10234, 10243, 10257, 10258, 10285, 10289, 10300,
       10304, 10319, 10320, 10335, 10355, 10358, 10398, 10400, 10424,
       10426, 10444, 10459, 10460, 10461, 10464, 10472, 10473, 10482,
       10491, 10491, 10508, 10518, 10527, 10530, 10531, 10538, 10545,
       10546, 10547, 10554, 10555, 10563, 10566, 10572, 10573, 10574,
       10629, 10634, 10634, 10649, 10663, 10664, 10665, 10683, 10710,
       10712, 10722, 10724, 10742, 10747, 10755, 10755, 10758, 10765,
       10769, 10782, 10786, 10790, 10796, 10797, 10801, 10803, 10814,
       10837, 10850, 10870, 10877, 10880, 10896, 10898, 10913, 10919,
       10923, 10930, 10942, 10965, 10972, 10979, 10998, 10999, 11009,
       11024, 11027, 11036, 11045, 11049, 11054, 11062, 11085, 11089,
       11100, 11104, 11130, 11135, 11142, 11145, 11156, 11161, 11167,
       11175, 11179,

In [18]:
# Do you think the data in the array is permanently sorted ?
# Lets check it by printing the contents of the array once again 
sal

# Lets figure out how to sort the array elements permanently ! 

array([16610, 11432, 17993, 10712, 16787, 12940, 13328, 16097, 11988,
       14433, 13582, 15349, 14590, 16172, 12512, 11524, 19291, 18185,
       13564, 12193, 13250, 18415, 17969, 13620, 18559, 14367, 14831,
       14625, 14754, 19205, 12138, 13277, 19274, 17984, 13417, 16875,
       13486, 12655, 10233, 14751, 14005, 11446, 13203, 17281, 15062,
       16600, 15234, 13255, 14938, 16375, 13000, 10547, 14937, 14316,
       16784, 17355, 19587, 14345, 18855, 11045, 15581, 16785, 11877,
       16603, 10147, 14034, 19488, 19086, 15832, 16974, 11439, 13317,
       15662, 14983, 15880, 11261, 15175, 15367, 12245, 15110, 13441,
       18124, 14592, 19234, 14670, 19403, 10304, 11884, 10998, 17349,
       12045, 17786, 11348, 12839, 17458, 14296, 17705, 10758, 13614,
       14790, 13075, 11863, 16505, 13839, 12112, 15344, 18616, 15708,
       12689, 11303, 19977, 13584, 14793, 18661, 15486, 11324, 10149,
       17434, 19951, 15815, 11206, 19782, 10572, 13653, 19233, 18894,
       13803, 19961,

In [19]:
#Getting the values in descending order
descending_sort = np.sort(sal)[::-1] # Storing the results of sort operation in a new array
descending_sort

array([19998, 19990, 19988, 19984, 19977, 19961, 19951, 19946, 19944,
       19937, 19934, 19920, 19917, 19916, 19910, 19895, 19884, 19861,
       19828, 19809, 19805, 19795, 19794, 19793, 19793, 19788, 19787,
       19782, 19781, 19764, 19746, 19732, 19718, 19716, 19709, 19693,
       19685, 19669, 19641, 19640, 19631, 19611, 19587, 19580, 19566,
       19560, 19556, 19542, 19534, 19514, 19510, 19507, 19494, 19493,
       19488, 19451, 19449, 19443, 19437, 19413, 19403, 19396, 19395,
       19393, 19390, 19386, 19385, 19377, 19370, 19355, 19327, 19304,
       19294, 19291, 19287, 19274, 19253, 19246, 19244, 19242, 19234,
       19233, 19223, 19218, 19209, 19208, 19205, 19202, 19187, 19183,
       19173, 19167, 19152, 19141, 19141, 19140, 19138, 19120, 19115,
       19110, 19086, 19084, 19077, 19043, 19037, 19017, 19017, 19010,
       19008, 18991, 18966, 18952, 18938, 18924, 18914, 18910, 18909,
       18909, 18908, 18906, 18895, 18894, 18858, 18855, 18848, 18841,
       18840, 18807,

In [20]:
print("The top 10 highest salaries are: ", g[0:11])

NameError: name 'g' is not defined

# Q-13) 
## The HR wants to know how many employees have an annual salary of 14,999 USD. The HR wants replace these salary values by a new value of 15,000 USD. How can you accomplish this task? The array 'sal' contains the salaries of all employees.


In [21]:
np.count_nonzero(sal == 14999) # Finding the occurance of value 14999

# Note : The count could be zero at times since the array "sal" contains randomly 
# generated values. Try checking for other values instead of 14999 

0

In [22]:
# Note : Run the below code only the result of the above code is a non zero value ! 
#round_sal = np.where(sal == 14999, 15000, sal) # Replacing values with 14999 to 15000
#print(round_sal)

In [23]:
np.count_nonzero(out == 25000) # We are counting the occurance of 25000 in the data


NameError: name 'out' is not defined

# Reading data from csv files using NumPy

# Q14) How can you read data from a csv file that contains the column "Employee ID" with 20 values?

In [24]:
pwd #Finding present working directory

'C:\\Users\\Vinod kumar raju\\Downloads\\Imad\\Course 4\\Sprint-1\\Sprint-1_V1'

### Ensure that the csv file is present in the current working directory.

In [4]:
from numpy import genfromtxt

emp_code = genfromtxt('employee_code.csv', delimiter=';', skip_header=1)
emp_code 

FileNotFoundError: employee_code.csv not found.

In [26]:
pwd

'C:\\Users\\Vinod kumar raju\\Downloads\\Imad\\Course 4\\Sprint-1\\Sprint-1_V1'

# Alternate way of a reading a csv file

In [27]:
import csv
with open('employee_code.csv', 'r') as f:
    code = list(csv.reader(f, delimiter=';'))

code = np.array(code[1:])

In [28]:
code

array([['1010'],
       ['1011'],
       ['1012'],
       ['1013'],
       ['1014'],
       ['1015'],
       ['1016'],
       ['1017'],
       ['1018'],
       ['1019'],
       ['1020'],
       ['1021'],
       ['1022'],
       ['1023'],
       ['1024'],
       ['1025'],
       ['1026'],
       ['1027'],
       ['1028'],
       ['1029']], dtype='<U4')

In [29]:
from numpy import genfromtxt

emp_code = genfromtxt('employee_code.csv', delimiter=';', skip_header=1)
emp_code

array([1010., 1011., 1012., 1013., 1014., 1015., 1016., 1017., 1018.,
       1019., 1020., 1021., 1022., 1023., 1024., 1025., 1026., 1027.,
       1028., 1029.])