In [5]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


You should consider upgrading via the 'C:\Users\ADMIN\AppData\Local\Programs\Python\Python310\python.exe -m pip install --upgrade pip' command.


In [6]:
#import numpy library

import numpy

In [7]:
#2nd way
import numpy as np

In [8]:
#3rd way #if your library is massive

from numpy import add #sub,multi..........

In [9]:
#np.  press tab!!!!

In [10]:
add()

TypeError: add() takes from 2 to 3 positional arguments but 0 were given

In [11]:
#np.add #press shift + tab

In [12]:
#1

In [65]:
import numpy as np
empid = np.arange(1,1001) # The arange function returns an array of integers starting from 1 to 1000 
print(empid)
# 1 is inclusive number and 1001 is exclusive number! 

[   1    2    3    4    5    6    7    8    9   10   11   12   13   14
   15   16   17   18   19   20   21   22   23   24   25   26   27   28
   29   30   31   32   33   34   35   36   37   38   39   40   41   42
   43   44   45   46   47   48   49   50   51   52   53   54   55   56
   57   58   59   60   61   62   63   64   65   66   67   68   69   70
   71   72   73   74   75   76   77   78   79   80   81   82   83   84
   85   86   87   88   89   90   91   92   93   94   95   96   97   98
   99  100  101  102  103  104  105  106  107  108  109  110  111  112
  113  114  115  116  117  118  119  120  121  122  123  124  125  126
  127  128  129  130  131  132  133  134  135  136  137  138  139  140
  141  142  143  144  145  146  147  148  149  150  151  152  153  154
  155  156  157  158  159  160  161  162  163  164  165  166  167  168
  169  170  171  172  173  174  175  176  177  178  179  180  181  182
  183  184  185  186  187  188  189  190  191  192  193  194  195  196
  197 

In [13]:
#step size
arr = np.arange(1,1001) # The arange function returns an array of integers starting from 1 to 1000 

In [14]:
arr

array([   1,    2,    3,    4,    5,    6,    7,    8,    9,   10,   11,
         12,   13,   14,   15,   16,   17,   18,   19,   20,   21,   22,
         23,   24,   25,   26,   27,   28,   29,   30,   31,   32,   33,
         34,   35,   36,   37,   38,   39,   40,   41,   42,   43,   44,
         45,   46,   47,   48,   49,   50,   51,   52,   53,   54,   55,
         56,   57,   58,   59,   60,   61,   62,   63,   64,   65,   66,
         67,   68,   69,   70,   71,   72,   73,   74,   75,   76,   77,
         78,   79,   80,   81,   82,   83,   84,   85,   86,   87,   88,
         89,   90,   91,   92,   93,   94,   95,   96,   97,   98,   99,
        100,  101,  102,  103,  104,  105,  106,  107,  108,  109,  110,
        111,  112,  113,  114,  115,  116,  117,  118,  119,  120,  121,
        122,  123,  124,  125,  126,  127,  128,  129,  130,  131,  132,
        133,  134,  135,  136,  137,  138,  139,  140,  141,  142,  143,
        144,  145,  146,  147,  148,  149,  150,  1

In [15]:
type(arr)

numpy.ndarray

In [18]:
# How to create numpy arrays

a = np.array([1,2,3,4,5,]) #Homogenous array

b = np.array([10,20,30,40,50])

print(a+b)
print(a-b)
print(a/b)
print(a*b)

[11 22 33 44 55]
[ -9 -18 -27 -36 -45]
[0.1 0.1 0.1 0.1 0.1]
[ 10  40  90 160 250]


In [19]:
#2

In [ ]:
# start stop size

In [23]:
print(np.random.randint(10,20,10))
print(np.random.uniform(10,20,10)) #Generates random numbers from uniform distribution

[15 19 19 19 15 15 18 14 16 19]
[11.58821552 14.89023593 11.93074235 14.16333867 18.20982127 13.51989424
 10.95366462 13.05278929 16.33885143 17.30077109]


In [ ]:
#NUMPY --> RANDOM --> randint........

In [20]:
#from random usind randint (random integer)
bonus = np.random.randint(100,300,1000)
print(bonus)

[183 212 180 176 111 165 116 238 198 273 205 131 109 193 220 171 278 112
 257 250 182 183 212 196 108 113 144 247 264 239 185 212 259 159 299 168
 252 263 248 287 237 279 175 186 229 287 124 156 286 145 180 167 267 172
 275 222 255 106 234 100 192 213 247 275 141 100 173 137 247 115 249 146
 232 250 211 203 182 144 208 227 219 120 254 243 231 208 244 240 206 107
 293 281 193 284 264 171 132 190 198 130 163 283 206 276 283 115 156 164
 268 257 170 132 183 168 189 247 102 299 209 124 165 123 233 137 262 237
 113 139 208 191 130 112 169 202 268 212 154 270 199 269 150 106 299 113
 261 259 158 116 179 248 206 107 161 238 144 171 286 118 207 184 127 243
 279 185 288 276 278 296 222 289 163 237 200 206 139 174 293 111 255 218
 115 166 115 221 276 292 155 266 208 164 248 259 133 102 178 273 171 145
 226 101 254 246 147 228 207 229 278 133 252 135 133 136 247 255 129 144
 292 157 171 118 158 298 182 295 140 136 107 123 152 275 137 282 227 234
 245 166 255 202 227 138 192 238 210 297 201 160 23

In [24]:
#3

In [25]:
sal = np.random.randint(10000,20000,1000)
print(sal) # Checking how the salary data looks like..

[19165 19870 16726 14628 10992 11965 12642 18598 17701 19416 11606 15943
 19603 11058 17809 14958 11169 12007 19422 17418 14140 18818 19748 17467
 10955 14772 11451 13955 12880 11043 18073 18398 17060 10978 14618 12761
 16966 10819 16283 18257 17151 14960 15740 12133 11829 18593 15623 17256
 16556 17519 11770 12040 11095 15211 14347 10399 18654 19707 12510 16588
 17456 14123 14977 15303 18168 18169 19113 15910 17226 10940 10839 11638
 12941 10875 12164 17571 16251 19608 14851 14286 16399 18510 13878 17558
 10836 10430 18823 15935 11610 14047 11494 19112 12144 13044 13853 11375
 15025 15067 11371 11771 14416 19116 19548 16419 12368 13135 13828 15480
 13734 14781 17385 14807 11761 16712 11026 17482 11343 16854 18341 18921
 17739 11057 15187 17935 11796 15302 19352 15323 18608 19418 12823 10094
 18475 17608 17968 12459 13307 18169 11479 14343 11001 13717 10702 16664
 15168 16327 15135 16628 11369 15024 16550 18780 11942 18205 10655 15768
 10833 11222 15755 12706 13997 18508 19307 18781 16

In [26]:
#Finding average salary

avgsal = np.mean(sal)
print("The average annual salary of employees: ", avgsal)

The average annual salary of employees:  15149.922


In [27]:
#4

In [28]:
newctc = sal+bonus # Numpy arrays allows 2 equal size array elements to be added , element by element 
newctc


array([19348, 20082, 16906, 14804, 11103, 12130, 12758, 18836, 17899,
       19689, 11811, 16074, 19712, 11251, 18029, 15129, 11447, 12119,
       19679, 17668, 14322, 19001, 19960, 17663, 11063, 14885, 11595,
       14202, 13144, 11282, 18258, 18610, 17319, 11137, 14917, 12929,
       17218, 11082, 16531, 18544, 17388, 15239, 15915, 12319, 12058,
       18880, 15747, 17412, 16842, 17664, 11950, 12207, 11362, 15383,
       14622, 10621, 18909, 19813, 12744, 16688, 17648, 14336, 15224,
       15578, 18309, 18269, 19286, 16047, 17473, 11055, 11088, 11784,
       13173, 11125, 12375, 17774, 16433, 19752, 15059, 14513, 16618,
       18630, 14132, 17801, 11067, 10638, 19067, 16175, 11816, 14154,
       11787, 19393, 12337, 13328, 14117, 11546, 15157, 15257, 11569,
       11901, 14579, 19399, 19754, 16695, 12651, 13250, 13984, 15644,
       14002, 15038, 17555, 14939, 11944, 16880, 11215, 17729, 11445,
       17153, 18550, 19045, 17904, 11180, 15420, 18072, 12058, 15539,
       19465, 15462,

In [29]:
#5 slicing [start -index : end-index : step]

In [34]:
empid = np.arange(1,1001) # The object "e,pid" contains the employee codes from 1 to 1000
empid[1::2]
# One could also use  empid[1:1001:2]

array([   2,    4,    6,    8,   10,   12,   14,   16,   18,   20,   22,
         24,   26,   28,   30,   32,   34,   36,   38,   40,   42,   44,
         46,   48,   50,   52,   54,   56,   58,   60,   62,   64,   66,
         68,   70,   72,   74,   76,   78,   80,   82,   84,   86,   88,
         90,   92,   94,   96,   98,  100,  102,  104,  106,  108,  110,
        112,  114,  116,  118,  120,  122,  124,  126,  128,  130,  132,
        134,  136,  138,  140,  142,  144,  146,  148,  150,  152,  154,
        156,  158,  160,  162,  164,  166,  168,  170,  172,  174,  176,
        178,  180,  182,  184,  186,  188,  190,  192,  194,  196,  198,
        200,  202,  204,  206,  208,  210,  212,  214,  216,  218,  220,
        222,  224,  226,  228,  230,  232,  234,  236,  238,  240,  242,
        244,  246,  248,  250,  252,  254,  256,  258,  260,  262,  264,
        266,  268,  270,  272,  274,  276,  278,  280,  282,  284,  286,
        288,  290,  292,  294,  296,  298,  300,  3

In [32]:
arr2 = np.random.randint(10,20,30)

In [33]:
arr2

array([11, 11, 19, 18, 15, 12, 10, 14, 19, 15, 18, 15, 18, 13, 10, 13, 11,
       15, 13, 16, 13, 17, 11, 12, 10, 10, 14, 15, 18, 15])

In [36]:
#6

In [37]:
#print(b) # Already existing set of bonus details for 1000 employees 
updatedbonus = np.add(bonus,200)
updatedbonus

array([383, 412, 380, 376, 311, 365, 316, 438, 398, 473, 405, 331, 309,
       393, 420, 371, 478, 312, 457, 450, 382, 383, 412, 396, 308, 313,
       344, 447, 464, 439, 385, 412, 459, 359, 499, 368, 452, 463, 448,
       487, 437, 479, 375, 386, 429, 487, 324, 356, 486, 345, 380, 367,
       467, 372, 475, 422, 455, 306, 434, 300, 392, 413, 447, 475, 341,
       300, 373, 337, 447, 315, 449, 346, 432, 450, 411, 403, 382, 344,
       408, 427, 419, 320, 454, 443, 431, 408, 444, 440, 406, 307, 493,
       481, 393, 484, 464, 371, 332, 390, 398, 330, 363, 483, 406, 476,
       483, 315, 356, 364, 468, 457, 370, 332, 383, 368, 389, 447, 302,
       499, 409, 324, 365, 323, 433, 337, 462, 437, 313, 339, 408, 391,
       330, 312, 369, 402, 468, 412, 354, 470, 399, 469, 350, 306, 499,
       313, 461, 459, 358, 316, 379, 448, 406, 307, 361, 438, 344, 371,
       486, 318, 407, 384, 327, 443, 479, 385, 488, 476, 478, 496, 422,
       489, 363, 437, 400, 406, 339, 374, 493, 311, 455, 418, 31

In [38]:
#7

In [39]:
sal.size # The size tells us the number of data items in the array "sal"

1000

In [41]:
index = np.where(sal > 15000)
print(index)
# index contains the positions of the array "sal" where salary > 15000 is satisfied
print(sal[index]) 
#Here the output represents all the salaries more than 15000 USD
#The next step is to find the total number of employees whose salary is greater than 15000

(array([  0,   1,   2,   7,   8,   9,  11,  12,  14,  18,  19,  21,  22,
        23,  30,  31,  32,  36,  38,  39,  40,  42,  45,  46,  47,  48,
        49,  53,  56,  57,  59,  60,  63,  64,  65,  66,  67,  68,  75,
        76,  77,  80,  81,  83,  86,  87,  91,  96,  97, 101, 102, 103,
       107, 110, 113, 115, 117, 118, 119, 120, 122, 123, 125, 126, 127,
       128, 129, 132, 133, 134, 137, 143, 144, 145, 146, 147, 149, 150,
       151, 153, 155, 158, 161, 162, 163, 164, 166, 167, 172, 173, 176,
       177, 178, 181, 182, 185, 187, 188, 190, 193, 195, 196, 198, 199,
       200, 203, 204, 205, 206, 207, 208, 214, 215, 216, 217, 219, 220,
       222, 223, 225, 226, 227, 228, 230, 232, 234, 235, 236, 238, 239,
       240, 241, 244, 246, 251, 252, 257, 259, 261, 262, 263, 264, 266,
       269, 271, 272, 274, 275, 276, 279, 285, 286, 287, 288, 294, 297,
       298, 299, 300, 301, 303, 304, 307, 308, 310, 313, 314, 315, 316,
       317, 318, 319, 320, 324, 326, 328, 329, 334, 336, 337, 3

In [42]:
print("Total number of emplyees who's salary is more than $7500 is:", np.size(index) )

Total number of emplyees who's salary is more than $7500 is: 520


In [46]:
# shift + tab (drop down)

In [43]:
a1 = np.array([10,20,15,46,34])
b1 = np.array([12,15,13,56,71])

#max number from each index

c = np.where(a1>b1,a1,b1)
c

array([12, 20, 15, 56, 71])

In [45]:
np.max(a1)

46

In [44]:
a1.max()

46

In [47]:
#8

In [48]:
dup = empid.copy() # We are cloning a copy to demonstrate deletion of data
dup

array([   1,    2,    3,    4,    5,    6,    7,    8,    9,   10,   11,
         12,   13,   14,   15,   16,   17,   18,   19,   20,   21,   22,
         23,   24,   25,   26,   27,   28,   29,   30,   31,   32,   33,
         34,   35,   36,   37,   38,   39,   40,   41,   42,   43,   44,
         45,   46,   47,   48,   49,   50,   51,   52,   53,   54,   55,
         56,   57,   58,   59,   60,   61,   62,   63,   64,   65,   66,
         67,   68,   69,   70,   71,   72,   73,   74,   75,   76,   77,
         78,   79,   80,   81,   82,   83,   84,   85,   86,   87,   88,
         89,   90,   91,   92,   93,   94,   95,   96,   97,   98,   99,
        100,  101,  102,  103,  104,  105,  106,  107,  108,  109,  110,
        111,  112,  113,  114,  115,  116,  117,  118,  119,  120,  121,
        122,  123,  124,  125,  126,  127,  128,  129,  130,  131,  132,
        133,  134,  135,  136,  137,  138,  139,  140,  141,  142,  143,
        144,  145,  146,  147,  148,  149,  150,  1

In [49]:
new_dup = np.delete(dup, (5-1, 124-1, 200-1, 332-1, 420-1, 589-1, 665-1, 743-1, 887-1,901-1), axis=0)
new_dup

array([   1,    2,    3,    4,    6,    7,    8,    9,   10,   11,   12,
         13,   14,   15,   16,   17,   18,   19,   20,   21,   22,   23,
         24,   25,   26,   27,   28,   29,   30,   31,   32,   33,   34,
         35,   36,   37,   38,   39,   40,   41,   42,   43,   44,   45,
         46,   47,   48,   49,   50,   51,   52,   53,   54,   55,   56,
         57,   58,   59,   60,   61,   62,   63,   64,   65,   66,   67,
         68,   69,   70,   71,   72,   73,   74,   75,   76,   77,   78,
         79,   80,   81,   82,   83,   84,   85,   86,   87,   88,   89,
         90,   91,   92,   93,   94,   95,   96,   97,   98,   99,  100,
        101,  102,  103,  104,  105,  106,  107,  108,  109,  110,  111,
        112,  113,  114,  115,  116,  117,  118,  119,  120,  121,  122,
        123,  125,  126,  127,  128,  129,  130,  131,  132,  133,  134,
        135,  136,  137,  138,  139,  140,  141,  142,  143,  144,  145,
        146,  147,  148,  149,  150,  151,  152,  1

In [50]:
#9

In [51]:
# Lets check if the element 5 is actually deleted from the array "new_dup"
5 in new_dup # This line of code would check if the data 5 is present in array "d"
print()

False

In [52]:
#10

In [60]:
# Lets find the index locations of data items 101 and 201, and then delete 
pos101 = np.where(new_dup == 101)
pos201 = np.where(new_dup == 201)
print(pos101,pos201)
# Complete the code to perform the delete operation 
poss = np.delete(new_dup (100-1, 197-1))
np.delete(new_dup (pos101, pos201))


(array([99], dtype=int64),) (array([197], dtype=int64),)


TypeError: 'numpy.ndarray' object is not callable

In [61]:
#11

In [62]:
newid = np.arange(1001,1011) # Lets generate the new set of employee ID's
print(newid)

[1001 1002 1003 1004 1005 1006 1007 1008 1009 1010]


In [63]:
empid=np.append(empid,newid) # We are appending the new employee ID's to the original array "empid"
print(empid)

[   1    2    3 ... 1008 1009 1010]


In [67]:
#12 SORTING

In [66]:
#Getting the values in ascending order
np.sort(sal) # The salary of the employees are in the range of 10000 to 20000 USD p.a 

array([10006, 10030, 10054, 10056, 10094, 10094, 10107, 10123, 10129,
       10131, 10164, 10165, 10167, 10184, 10186, 10190, 10196, 10200,
       10201, 10215, 10218, 10225, 10260, 10281, 10285, 10305, 10317,
       10333, 10341, 10364, 10399, 10400, 10409, 10430, 10477, 10500,
       10524, 10532, 10534, 10573, 10581, 10600, 10600, 10605, 10610,
       10617, 10629, 10631, 10644, 10645, 10655, 10657, 10667, 10700,
       10702, 10722, 10741, 10743, 10784, 10786, 10786, 10798, 10799,
       10805, 10809, 10817, 10819, 10824, 10824, 10832, 10833, 10833,
       10834, 10836, 10839, 10842, 10851, 10859, 10863, 10875, 10905,
       10908, 10914, 10927, 10927, 10935, 10940, 10950, 10955, 10960,
       10978, 10979, 10980, 10981, 10987, 10992, 11001, 11021, 11026,
       11027, 11043, 11057, 11058, 11059, 11060, 11081, 11084, 11092,
       11095, 11110, 11119, 11122, 11144, 11169, 11183, 11202, 11205,
       11215, 11222, 11243, 11246, 11248, 11292, 11306, 11309, 11333,
       11337, 11343,

In [68]:
# Do you think the data in the array is permanently sorted ?
# Lets check it by printing the contents of the array once again 
sal

# Lets figure out how to sort the array elements permanently ! 

array([19165, 19870, 16726, 14628, 10992, 11965, 12642, 18598, 17701,
       19416, 11606, 15943, 19603, 11058, 17809, 14958, 11169, 12007,
       19422, 17418, 14140, 18818, 19748, 17467, 10955, 14772, 11451,
       13955, 12880, 11043, 18073, 18398, 17060, 10978, 14618, 12761,
       16966, 10819, 16283, 18257, 17151, 14960, 15740, 12133, 11829,
       18593, 15623, 17256, 16556, 17519, 11770, 12040, 11095, 15211,
       14347, 10399, 18654, 19707, 12510, 16588, 17456, 14123, 14977,
       15303, 18168, 18169, 19113, 15910, 17226, 10940, 10839, 11638,
       12941, 10875, 12164, 17571, 16251, 19608, 14851, 14286, 16399,
       18510, 13878, 17558, 10836, 10430, 18823, 15935, 11610, 14047,
       11494, 19112, 12144, 13044, 13853, 11375, 15025, 15067, 11371,
       11771, 14416, 19116, 19548, 16419, 12368, 13135, 13828, 15480,
       13734, 14781, 17385, 14807, 11761, 16712, 11026, 17482, 11343,
       16854, 18341, 18921, 17739, 11057, 15187, 17935, 11796, 15302,
       19352, 15323,

In [75]:
#Getting the values in descending order
descending_sort = np.sort(sal)[::-1] # Storing the results of sort operation in a new array
descending_sort

array([19998, 19975, 19945, 19927, 19910, 19891, 19887, 19883, 19878,
       19870, 19870, 19860, 19855, 19854, 19848, 19842, 19841, 19834,
       19832, 19819, 19808, 19804, 19795, 19794, 19785, 19785, 19757,
       19748, 19732, 19722, 19720, 19719, 19707, 19699, 19673, 19667,
       19659, 19656, 19643, 19643, 19642, 19641, 19626, 19608, 19603,
       19586, 19583, 19573, 19549, 19548, 19534, 19522, 19513, 19483,
       19482, 19477, 19473, 19450, 19439, 19438, 19427, 19422, 19420,
       19418, 19416, 19392, 19390, 19389, 19382, 19381, 19377, 19352,
       19347, 19326, 19307, 19303, 19298, 19284, 19271, 19239, 19234,
       19223, 19220, 19214, 19211, 19186, 19183, 19173, 19165, 19126,
       19116, 19113, 19113, 19112, 19098, 19092, 19092, 19081, 19052,
       19051, 19050, 19039, 19031, 19023, 19007, 19007, 19006, 19002,
       19000, 18994, 18989, 18987, 18975, 18969, 18960, 18955, 18921,
       18916, 18916, 18903, 18901, 18897, 18894, 18885, 18882, 18861,
       18860, 18857,

In [77]:
print("The top 10 highest salaries are: ", descending_sort[0:10])

The top 10 highest salaries are:  [19998 19975 19945 19927 19910 19891 19887 19883 19878 19870]


In [72]:
sorted(sal,reverse=True)[:10]

[19998, 19975, 19945, 19927, 19910, 19891, 19887, 19883, 19878, 19870]

In [78]:
#13

In [79]:
all = np.array([1,2,3,4,0,0,0,0])
np.count_nonzero(all)    #counts only natural numbers

4

In [80]:
all.size # count or size

8

In [81]:
all.shape # 8 rows (imagine it vertically)

(8,)

In [82]:
all.ndim # dimensions id array so its giving '1'

1

In [86]:
np.count_nonzero(sal == 14999) # Finding the occurance of value 14999

# Note : The count could be zero at times since the array "sal" contains randomly 
# generated values. Try checking for other values instead of 14999 

0

In [87]:
# Note : Run the below code only the result of the above code is a non zero value ! 
round_sal = np.where(sal == 14999, 15000, sal) # Replacing values with 14999 to 15000
print(round_sal)

[19165 19870 16726 14628 10992 11965 12642 18598 17701 19416 11606 15943
 19603 11058 17809 14958 11169 12007 19422 17418 14140 18818 19748 17467
 10955 14772 11451 13955 12880 11043 18073 18398 17060 10978 14618 12761
 16966 10819 16283 18257 17151 14960 15740 12133 11829 18593 15623 17256
 16556 17519 11770 12040 11095 15211 14347 10399 18654 19707 12510 16588
 17456 14123 14977 15303 18168 18169 19113 15910 17226 10940 10839 11638
 12941 10875 12164 17571 16251 19608 14851 14286 16399 18510 13878 17558
 10836 10430 18823 15935 11610 14047 11494 19112 12144 13044 13853 11375
 15025 15067 11371 11771 14416 19116 19548 16419 12368 13135 13828 15480
 13734 14781 17385 14807 11761 16712 11026 17482 11343 16854 18341 18921
 17739 11057 15187 17935 11796 15302 19352 15323 18608 19418 12823 10094
 18475 17608 17968 12459 13307 18169 11479 14343 11001 13717 10702 16664
 15168 16327 15135 16628 11369 15024 16550 18780 11942 18205 10655 15768
 10833 11222 15755 12706 13997 18508 19307 18781 16

In [90]:
np.count_nonzero(round_sal == 25000) # We are counting the occurance of 25000 in the data


0

In [83]:
#14

In [91]:
pwd #Finding present working directory

'e:\\'

In [98]:
from numpy import genfromtxt

emp_code = genfromtxt('DS1_C4_S1_Employee_Code_PracticeBrief.csv', delimiter=';', skip_header=1)
emp_code 

array([1010., 1011., 1012., 1013., 1014., 1015., 1016., 1017., 1018.,
       1019., 1020., 1021., 1022., 1023., 1024., 1025., 1026., 1027.,
       1028., 1029.])

In [99]:
emp_code = genfromtxt('DS1_C4_S1_Employee_Code_PracticeBrief.csv', delimiter=';', skip_header=True)
emp_code 
#in the data skip header is reffering to the heading of the column 'employee_code '

array([1010., 1011., 1012., 1013., 1014., 1015., 1016., 1017., 1018.,
       1019., 1020., 1021., 1022., 1023., 1024., 1025., 1026., 1027.,
       1028., 1029.])

In [102]:
#checking whether int or float or boolean
check = np.array(emp_code,dtype=np.int16)
check

array([1010, 1011, 1012, 1013, 1014, 1015, 1016, 1017, 1018, 1019, 1020,
       1021, 1022, 1023, 1024, 1025, 1026, 1027, 1028, 1029], dtype=int16)

In [103]:
check.dtype #dtype attribute to give you the data type

dtype('int16')

In [104]:
#alternate way to read a csv file

In [108]:
import csvDS1_C4_S1_Employee_Code_PracticeBrief.csv
with open('', 'r') as f:
    code = list(csv.reader(f, delimiter=';'))

code = np.array(code[1:])

ModuleNotFoundError: No module named 'csvDS1_C4_S1_Employee_Code_PracticeBrief'

In [106]:
code

NameError: name 'code' is not defined