In [ ]:
import numpy as np
from numpy import genfromtxt

In [4]:
admission = genfromtxt('DS1_C4_S2_Admission_Predict_Practice.csv', delimiter=',', skip_header=True)
print(admission)

[[  1.   337.   118.   ...   9.65   1.     0.92]
 [  2.   324.   107.   ...   8.87   1.     0.76]
 [  3.   316.   104.   ...   8.     1.     0.72]
 ...
 [398.   330.   116.   ...   9.45   1.     0.91]
 [399.   312.   103.   ...   8.78   0.     0.67]
 [400.   333.   117.   ...   9.66   1.     0.95]]


# TASK 1

In [87]:
GRE=admission[:,1]
#GRE

In [6]:
GRE1=np.where(GRE>320)
print('students having  gre score Greater than 320 is: ' ,GRE[GRE1])

students having  gre score Greater than 320 is:  [337. 324. 322. 330. 321. 323. 325. 327. 328. 325. 328. 334. 336. 340.
 322. 327. 338. 340. 331. 332. 326. 322. 329. 339. 321. 327. 334. 324.
 322. 325. 325. 327. 328. 332. 336. 321. 329. 327. 340. 322. 340. 331.
 332. 323. 322. 326. 329. 338. 331. 321. 327. 335. 334. 323. 326. 333.
 339. 323. 333. 326. 329. 332. 331. 340. 325. 326. 339. 334. 332. 321.
 324. 326. 329. 322. 334. 322. 323. 321. 329. 327. 335. 331. 324. 324.
 323. 322. 336. 340. 334. 325. 328. 338. 333. 331. 330. 322. 321. 324.
 324. 324. 330. 326. 325. 329. 324. 325. 328. 324. 321. 335. 321. 324.
 326. 331. 327. 324. 325. 327. 322. 329. 321. 340. 331. 336. 324. 330.
 322. 323. 321. 323. 325. 328. 324. 327. 323. 326. 324. 327. 325. 332.
 323. 324. 326. 325. 327. 321. 322. 334. 338. 330. 324. 336. 321. 322.
 324. 340. 335. 326. 329. 324. 325. 330. 333.]


In [7]:
print('total no of students having GRE no gretaer than 320 : ', GRE1[0].size)

total no of students having GRE no gretaer than 320 :  163


# TASK 2

In [88]:
TOEFL=admission[:,2]
#TOEFL

In [9]:
TOEFL1=np.where(TOEFL>110)
TOEFL2=(TOEFL[TOEFL1])
TOEFL2

array([118., 115., 111., 112., 114., 116., 119., 119., 120., 118., 114.,
       112., 117., 113., 114., 119., 111., 116., 112., 111., 112., 114.,
       115., 118., 112., 111., 114., 112., 120., 115., 115., 120., 119.,
       113., 112., 111., 117., 116., 117., 119., 113., 112., 112., 118.,
       114., 112., 113., 116., 118., 115., 120., 112., 113., 114., 116.,
       114., 116., 112., 111., 117., 113., 111., 111., 119., 113., 118.,
       115., 112., 111., 114., 118., 120., 120., 120., 119., 117., 116.,
       112., 113., 112., 111., 113., 111., 112., 114., 115., 114., 111.,
       115., 114., 119., 111., 113., 113., 111., 112., 116., 118., 114.,
       120., 114., 112., 112., 111., 113., 116., 112., 113., 111., 118.,
       116., 115., 114., 119., 113., 117., 112., 111., 116., 117.])

In [10]:
c=(admission[TOEFL1])
print('data of students who are having TOEFL more than 110 :\n' ,c)

data of students who are having TOEFL more than 110 :
 [[  1.   337.   118.   ...   9.65   1.     0.92]
 [  6.   330.   115.   ...   9.34   1.     0.9 ]
 [ 12.   327.   111.   ...   9.     1.     0.84]
 ...
 [395.   329.   111.   ...   9.23   1.     0.89]
 [398.   330.   116.   ...   9.45   1.     0.91]
 [400.   333.   117.   ...   9.66   1.     0.95]]


In [100]:
#print('students having TOEFL more than 310 and their chances of admission : \n',c[:,[0,1,8]])   **

# TASK 3

In [14]:
GREsort=np.sort(GRE)[::-1]
#GREsort
max_GRE=GREsort[:11]
max_GRE



array([340., 340., 340., 340., 340., 340., 340., 340., 339., 339., 339.])

In [15]:
TOEFLsort=np.sort(TOEFL)[::-1]
max_TOEFL=TOEFLsort[:8]


# TASK 4

In [96]:
GRE
SOP=admission[:,4]
SOP
RE=admission[:,7]


In [17]:
fellowship=np.where((GRE>300) & (GRE<305) & (SOP==3.5) & (RE==1))

In [18]:
fellowship

(array([112, 209, 357], dtype=int64),)

In [19]:
fellowship1=admission[fellowship]

In [20]:
fellowship1

array([[113.  , 301.  , 107.  ,   3.  ,   3.5 ,   3.5 ,   8.34,   1.  ,
          0.62],
       [210.  , 301.  , 104.  ,   3.  ,   3.5 ,   4.  ,   8.12,   1.  ,
          0.68],
       [358.  , 301.  , 104.  ,   2.  ,   3.5 ,   3.5 ,   7.89,   1.  ,
          0.68]])

In [21]:
print('to offer fellowship the serial no.s and TOEFL score n of students is:\n', fellowship1[:,[0,2]])

to offer fellowship the serial no.s and TOEFL score n of students is:
 [[113. 107.]
 [210. 104.]
 [358. 104.]]


# TASK 5

In [86]:
serial_no=admission[0:,0]
serial_no
serial_no.size

400

In [23]:
scholarship=np.random.randint(5000,10000,size=(400,1))

In [92]:
#scholarship

In [25]:
admission_new=np.concatenate((admission,scholarship),axis=1)

In [26]:
admission_new=np.array(admission_new,dtype=np.int64) #it is used to remove that 23e+1313 type of data

In [27]:
admission_new

array([[   1,  337,  118, ...,    1,    0, 8090],
       [   2,  324,  107, ...,    1,    0, 5235],
       [   3,  316,  104, ...,    1,    0, 6981],
       ...,
       [ 398,  330,  116, ...,    1,    0, 5505],
       [ 399,  312,  103, ...,    0,    0, 9176],
       [ 400,  333,  117, ...,    1,    0, 7225]], dtype=int64)

In [28]:
no_of_Scholar=np.where(scholarship>9000)

In [29]:
print('no of students who recived sholarship more than 9000 are : ' , no_of_Scholar[0].size)

no of students who recived sholarship more than 9000 are :  82


# TASK 6

In [30]:
index=np.where(scholarship>9000)


In [31]:
g=scholarship[index]

In [32]:
index[0]
mo=admission_new[index[0]]

In [93]:
#print(mo[:,[0,4,5,9]]) **

# TASK 7

In [34]:
u=np.where((GRE>314) & (TOEFL>115) & (RE==1))

In [35]:
u

(array([  0,  22,  23,  24,  25,  32,  52,  70,  81,  97,  98, 107, 108,
        120, 121, 129, 138, 141, 143, 148, 151, 171, 176, 187, 193, 202,
        203, 212, 213, 214, 215, 259, 285, 286, 325, 337, 361, 372, 385,
        397, 399], dtype=int64),)

In [36]:
extra_scholar=admission_new[u]

In [94]:
#extra_scholar[:,[0,1,2,7,9]] **

In [38]:
u[0].size

41

In [39]:
# np.add((1000,scholarship)(where((GRE>314) & (TOEFL>115) & (RE==1))

In [40]:
ns=admission_new[u][:,9]
ns

array([8090, 6299, 5896, 8605, 5530, 6510, 7576, 9409, 5917, 5236, 8276,
       8044, 6614, 7863, 5316, 7646, 6814, 7344, 7916, 6993, 5061, 5205,
       7510, 9226, 9955, 8572, 6656, 8652, 8438, 9040, 8060, 9779, 8735,
       5339, 5119, 9244, 8203, 7793, 5922, 5505, 7225], dtype=int64)

In [84]:
admission_new[u][:,9]=ns+1000

# TASK 8

In [42]:
CGPA=admission[:,6]

In [83]:
#CGPA **

In [44]:
CGPA1=np.where((CGPA>8) & (CGPA<8.5))

In [45]:
CGPA1

(array([  4,   6,  10,  14,  15,  21,  30,  31,  36,  41,  49,  50,  53,
         59,  60,  61,  62,  77,  80,  86,  87,  88,  92, 100, 101, 102,
        103, 110, 112, 114, 122, 123, 124, 136, 137, 146, 149, 156, 157,
        158, 166, 167, 170, 178, 179, 180, 181, 184, 196, 197, 198, 201,
        207, 208, 209, 219, 223, 224, 225, 226, 231, 232, 233, 238, 241,
        247, 255, 261, 262, 266, 267, 269, 270, 273, 278, 293, 294, 302,
        304, 313, 314, 315, 317, 321, 322, 323, 324, 326, 331, 332, 340,
        342, 343, 349, 350, 352, 353, 355, 359, 363, 366, 369, 370, 379,
        383, 387, 389, 390], dtype=int64),)

In [46]:
CGPA1[0].size # count of CGPA 

108

In [47]:
CG=admission[CGPA1]

In [95]:
CG=np.array(CG,dtype=np.int64)
#CG

In [49]:
CG[:,6].size # count through the column

108

# TASK 9

In [50]:
SOP=admission[:,4]
LOR=admission[:,5]
m_SOP= np.mean(SOP)
m_LOR=np.mean(LOR)

In [51]:
print('average of SOP is : ',m_SOP)
print('average of LOR is : ',m_LOR)

average of SOP is :  3.4
average of LOR is :  3.4525


In [52]:
x=round((m_LOR-m_SOP)/m_LOR*100,3)

In [53]:
print('average LOR is more than SOP score by : ' , x)

average LOR is more than SOP score by :  1.521


# TASK 10

In [82]:
#scholarship

In [71]:
print('mean= ',np.mean(scholarship))
print('median= ', np.median(scholarship))
print('maximum= ',np.max(scholarship))
print('minimum= ',np.min(scholarship))
print('standard deviation= ',round(np.std(scholarship),3))
print('variance = ', round(np.var(scholarship),3))
#print('co variance=', np.cov(scholarship))

mean=  7524.1475
median=  7477.0
maximum=  9998
minimum=  5004
standard deviation=  1438.672
variance =  2069777.391


# TASK 11

In [81]:
chance=admission[:,8]
#chance

In [75]:
admission_chance=np.where(chance>0.95)
            

In [78]:
chance[admission_chance]

array([0.97, 0.96, 0.96, 0.96, 0.97, 0.96, 0.97, 0.97, 0.96, 0.96, 0.96])

In [79]:
print(admission[admission_chance][:,[1,2,6,8]])

[[336.   119.     9.8    0.97]
 [336.   112.     9.76   0.96]
 [340.   120.     9.5    0.96]
 [339.   114.     9.76   0.96]
 [340.   120.     9.92   0.97]
 [339.   116.     9.8    0.96]
 [340.   120.     9.91   0.97]
 [334.   120.     9.87   0.97]
 [333.   119.     9.78   0.96]
 [340.   113.     9.74   0.96]
 [335.   117.     9.82   0.96]]
