#  2 Dimensional Arrays  (Tabular Representation of Data)

# Q1) A company wishes to allocate the employee codes from 101 to 105 along with the ages 25, 26, 27, 28, and 29 (in years) to its employees. How can you represent this data using arrays?  

In [2]:
#Using 2D arrays you can accomplish this task
import numpy as np
emp_code = [101,102,103,104,105]
emp_age = [25,26,27,28,29]
emp_data = np.array([emp_code, emp_age])
emp_data

array([[101, 102, 103, 104, 105],
       [ 25,  26,  27,  28,  29]])

emp_data.shape 

In [2]:
emp_data.ndim #Checking array dimension

2

## Columnar view of the data: We would like to see the employee IDs along with the ages in a tabular orientation.


In [3]:
emp_data.T # We use the Transpose operation to change row and column positions 

array([[101,  25],
       [102,  26],
       [103,  27],
       [104,  28],
       [105,  29]])

### Creating  2D arrays with random numbers

In [4]:
#Genrating 2D arrays with the integer value from 1 to 4, with a shape of 3x3
np.random.randint(1, 5, size=(3, 3)) 
# The randint function generates random numbers between the range 1 to 5
# The size function transforms the data into 3 by 3 arrays


array([[2, 4, 3],
       [2, 1, 2],
       [2, 1, 3]])

# Q-2)

# Accessing the elements of 2D arrays

In [6]:
emp_data  # Printing the array contents 

array([[101, 102, 103, 104, 105],
       [ 25,  26,  27,  28,  29]])

### 2.1:  Display the ages of all the employees from the emp_data

In [10]:
#Displaying ages
emp_data[1] # would display the Row at location 1 from emp_data

array([25, 26, 27, 28, 29])

### 2.2:   Display all the employee codes.

In [11]:
#Displaying employee code
emp_data[0] # Index location 1 would display the Row at location 1 from emp_data

array([101, 102, 103, 104, 105])

### 2.3: Display the employee code of the employee with age 28.

In [12]:
emp_data # Displaying the contents of the emp_data array for quick reference !

array([[101, 102, 103, 104, 105],
       [ 25,  26,  27,  28,  29]])

In [15]:
#Display the employee code where the employee age is 28
emp_data[0][3] 

104

### 2.4: Display the ages of the employees aged from 27 years to 29 years.

In [16]:
emp_data # Displaying the contents of the emp_data array for quick reference !

array([[101, 102, 103, 104, 105],
       [ 25,  26,  27,  28,  29]])

In [17]:
emp_data[1][2:] 
# The notation 2: would print the data from index location 2 onwards till the end

array([27, 28, 29])

### 2.5: Display the employee codes from 102 to 104.

In [18]:
emp_data[0][1:4]

array([102, 103, 104])

### 2.6: How can you display the records of the employees with the employee codes from 102 to 104 along with their ages?

In [19]:
emp_data # Displaying the contents of the emp_data array for quick reference !

array([[101, 102, 103, 104, 105],
       [ 25,  26,  27,  28,  29]])

In [22]:
emp_data[0:2,1:4]

array([[102, 103, 104],
       [ 26,  27,  28]])

### 2.7: Find the age of the employee with the employee code 102.

In [23]:
emp_data # Displaying the contents of the emp_data array for quick reference !

array([[101, 102, 103, 104, 105],
       [ 25,  26,  27,  28,  29]])

In [24]:
Index=np.where(emp_data[0] == 102) # where function will return the index of the 
# condition is satisfied ! 
print(emp_data[1][Index])

# Note : Try the above code with numbers other than 102

[26]


# Updating 2D arrays: 

# Q-3)

### 3.1: The employee with the employee code 103 wants to update the age with a new age 31. How can you accomplish this task?

In [26]:
Index=np.where(emp_data[0] == 103)
emp_data[1][Index] = 31
print(emp_data[1][Index])

[31]


In [27]:
emp_data

array([[101, 102, 103, 104, 105],
       [ 25,  26,  31,  28,  29]])

### 3.2: The company wants to add the annual salaries of all the employees in the existing record. Add the annual salary of 35,000, 45,000, 40,000, 30,000, and 50,000 for the employees with the employee codes from 101 to 105, respectively. 

In [32]:
sal = np.array([35000, 45000, 40000, 30000, 50000])
emp_data1=np.append(emp_data, [sal],axis=0)

In [34]:
emp_data1

array([[  101,   102,   103,   104,   105],
       [   25,    26,    31,    28,    29],
       [35000, 45000, 40000, 30000, 50000]])

### 3.3: Display the records of the employees with the employee codes 101 to 103.

In [35]:
emp_data1[0:3,0:3]

array([[  101,   102,   103],
       [   25,    26,    31],
       [35000, 45000, 40000]])

### 3.4: The HR wants to update the salary of the employee with the employee code 102 with a new salary 43,500. Help the HR to accomplish this task.

In [36]:
Index1=np.where(emp_data[0] == 102)
emp_data1[2][Index1] = 43500
print(emp_data1[2][Index1])

[43500]


In [37]:
emp_data1

array([[  101,   102,   103,   104,   105],
       [   25,    26,    31,    28,    29],
       [35000, 43500, 40000, 30000, 50000]])

# Q-4) 2D Array's Manipulation:

### The CEO of the organization has suggested to present all possible reports related to employees’ data to the HR team to understand the spread of salaries of the employees to take the decision for future recruitment and managing human resources expenses. How can you accomplish this task?

### 4.1: Help Thomas, the financial analyst, to find the total annual salary of all employees.

In [38]:
total_salary = np.sum(emp_data1[2])
total_salary

198500

### 4.2: Help Thomas to calculate the average age of employees.

In [39]:
avg_age = np.mean(emp_data1[1])
avg_age

27.8

### 4.3: The company has hired a new employee who is 27 years old, with an annual salary of 37,000 with the employee code 106. Add the employee details in the existing record of employees.
    

In [41]:
b = np.array([[106],[27],[37000]])
emp_data1 = np.append(emp_data1, b, axis = 1)
print(emp_data1)

[[  101   102   103   104   105   106]
 [   25    26    31    28    29    27]
 [35000 43500 40000 30000 50000 37000]]


### 4.4: The employee with the code 103 wishes to resign from the current job position. The company needs to remove the employee's data and update the record. How can you accomplish this task?

In [44]:
emp_data1 = np.delete(emp_data1,2,axis = 1) 
emp_data1

array([[  101,   102,   104,   105,   106],
       [   25,    26,    28,    29,    27],
       [35000, 43500, 30000, 50000, 37000]])

### 4.5: The company has decided to give a bonus amount to all the employees who are getting the annual salary more than 35,000 USD. For this, the company needs to know the number of such employees along with their salaries. 

In [47]:
index1 = np.where(emp_data1[2] > 35000)
print(emp_data1[2][index1]) #Here the output represent all the salaries more than 30000 USD
s = emp_data1[2][index1].size # Count of salaries
print("Total number of emplyees who's salary is more than $35000:", s)

[43500 50000 37000]
Total number of emplyees who's salary is more than $35000: 3


In [48]:
index1

(array([1, 3, 4], dtype=int64),)

In [49]:
emp_data1[0:,[1,3,4]]

array([[  102,   105,   106],
       [   26,    29,    27],
       [43500, 50000, 37000]])

# Q-5) Matrix Manipulation: 
Note : Matrix is a 2D numerical array used for scientific calculuations.

Matrix Creation: Create a matrix of 3x3 in which each column represent roll_no, marks, and percentage of the students.

In [50]:
List = [[1,420,70],[2,480,80],[3,540,90]]
matrix = np.array(List)
print(matrix)

[[  1 420  70]
 [  2 480  80]
 [  3 540  90]]


Matrix Transpose: Perform the transpose of matrix so that each row represents roll_no, marks, and percentage of the students.

In [51]:
np.transpose(matrix)

array([[  1,   2,   3],
       [420, 480, 540],
       [ 70,  80,  90]])

Matrix arithmetic operations: Create another matrix of 3x3 with random values.

In [55]:
matrix1= np.empty((3,3), dtype=int)
print(matrix1)

[[4522051 5439571 5374031]
 [4259935 4390994 4784200]
 [4522068 5505091 5374037]]


In [56]:
#Matrix addition, subtraction, element-wise multiplication
sum = matrix + matrix1
print(sum)


[[4522052 5439991 5374101]
 [4259937 4391474 4784280]
 [4522071 5505631 5374127]]


In [57]:
sub = matrix - matrix1
print(sub)

[[-4522050 -5439151 -5373961]
 [-4259933 -4390514 -4784120]
 [-4522065 -5504551 -5373947]]


In [58]:
#Element-wise matrix multiplication
mul = matrix * matrix1
print(mul)

[[    4522051 -2010347476   376182170]
 [    8519870  2107677120   382736000]
 [   13566204 -1322218156   483663330]]


In [59]:
#Real-time matrix multiplication
mult= matrix.dot(matrix1)
print(mult)

[[ 2110239511 -2059953875 -1904046675]
 [-1879388954 -1736003754 -1557880274]
 [-1574050123 -1412053633 -1211713873]]


# Reading data from CSV file

## Axess is an e-commerce company in the US.  "shopping-data.CSV" contains the customer information. There are 4 columns in this dataset:  CustomerID, Age, Annual Income in USD, and Spending score (1 to 100).

In [60]:
pwd #Find present working directory

'C:\\Users\\ishan.singh'

In [39]:
#Make sure you have "shopping-data.csv" in your current working directory

In [62]:
from numpy import genfromtxt

cust_data = genfromtxt('shopping-data.csv', delimiter=',', skip_header=1)
print(cust_data)

[[  1.  19.  15.  39.]
 [  2.  21.  15.  81.]
 [  3.  20.  16.   6.]
 [  4.  23.  16.  77.]
 [  5.  31.  17.  40.]
 [  6.  22.  17.  76.]
 [  7.  35.  18.   6.]
 [  8.  23.  18.  94.]
 [  9.  64.  19.   3.]
 [ 10.  30.  19.  72.]
 [ 11.  67.  19.  14.]
 [ 12.  35.  19.  99.]
 [ 13.  58.  20.  15.]
 [ 14.  24.  20.  77.]
 [ 15.  37.  20.  13.]
 [ 16.  22.  20.  79.]
 [ 17.  35.  21.  35.]
 [ 18.  20.  21.  66.]
 [ 19.  52.  23.  29.]
 [ 20.  35.  23.  98.]
 [ 21.  35.  24.  35.]
 [ 22.  25.  24.  73.]
 [ 23.  46.  25.   5.]
 [ 24.  31.  25.  73.]
 [ 25.  54.  28.  14.]
 [ 26.  29.  28.  82.]
 [ 27.  45.  28.  32.]
 [ 28.  35.  28.  61.]
 [ 29.  40.  29.  31.]
 [ 30.  23.  29.  87.]
 [ 31.  60.  30.   4.]
 [ 32.  21.  30.  73.]
 [ 33.  53.  33.   4.]
 [ 34.  18.  33.  92.]
 [ 35.  49.  33.  14.]
 [ 36.  21.  33.  81.]
 [ 37.  42.  34.  17.]
 [ 38.  30.  34.  73.]
 [ 39.  36.  37.  26.]
 [ 40.  20.  37.  75.]
 [ 41.  65.  38.  35.]
 [ 42.  24.  38.  92.]
 [ 43.  48.  39.  36.]
 [ 44.  31.

## Q-1) The company wants targetted marketing for some specific customers whose spending score is more than 80.  Find the total number of such customers and display each of their details.

In [63]:
Spnd =cust_data[:, 3] # we are slicing the specific column containing the spending score
Spnd

array([39., 81.,  6., 77., 40., 76.,  6., 94.,  3., 72., 14., 99., 15.,
       77., 13., 79., 35., 66., 29., 98., 35., 73.,  5., 73., 14., 82.,
       32., 61., 31., 87.,  4., 73.,  4., 92., 14., 81., 17., 73., 26.,
       75., 35., 92., 36., 61., 28., 65., 55., 47., 42., 42., 52., 60.,
       54., 60., 45., 41., 50., 46., 51., 46., 56., 55., 52., 59., 51.,
       59., 50., 48., 59., 47., 55., 42., 49., 56., 47., 54., 53., 48.,
       52., 42., 51., 55., 41., 44., 57., 46., 58., 55., 60., 46., 55.,
       41., 49., 40., 42., 52., 47., 50., 42., 49., 41., 48., 59., 55.,
       56., 42., 50., 46., 43., 48., 52., 54., 42., 46., 48., 50., 43.,
       59., 43., 57., 56., 40., 58., 91., 29., 77., 35., 95., 11., 75.,
        9., 75., 34., 71.,  5., 88.,  7., 73., 10., 72.,  5., 93., 40.,
       87., 12., 97., 36., 74., 22., 90., 17., 88., 20., 76., 16., 89.,
        1., 78.,  1., 73., 35., 83.,  5., 93., 26., 75., 20., 95., 27.,
       63., 13., 75., 10., 92., 13., 86., 15., 69., 14., 90., 32

In [64]:
#printing all the score which are more than 80
Indx = np.where(Spnd > 80) # We are fetching the index positions of data items where spend score is > 80
spndscore_more_than_80 = Spnd[Indx] 
print(spndscore_more_than_80)

[81. 94. 99. 98. 82. 87. 92. 81. 92. 91. 95. 88. 93. 87. 97. 90. 88. 89.
 83. 93. 95. 92. 86. 90. 86. 88. 97. 85. 91. 83.]


In [65]:
print("Total number of customers who's spending score is more than 80 : ",spndscore_more_than_80.size)

Total number of customers who's spending score is more than 80 :  30


In [66]:
Indx

(array([  1,   7,  11,  19,  25,  29,  33,  35,  41, 123, 127, 135, 141,
        143, 145, 149, 151, 155, 161, 163, 167, 173, 175, 179, 181, 183,
        185, 189, 193, 199], dtype=int64),)

In [67]:
#Displaying data of all the customers who's spending score is more than 80
print(cust_data[Indx]) #$ We use that index location array to fetch the other information from the 
# Original 2D array ! 

[[  2.  21.  15.  81.]
 [  8.  23.  18.  94.]
 [ 12.  35.  19.  99.]
 [ 20.  35.  23.  98.]
 [ 26.  29.  28.  82.]
 [ 30.  23.  29.  87.]
 [ 34.  18.  33.  92.]
 [ 36.  21.  33.  81.]
 [ 42.  24.  38.  92.]
 [124.  39.  69.  91.]
 [128.  40.  71.  95.]
 [136.  29.  73.  88.]
 [142.  32.  75.  93.]
 [144.  32.  76.  87.]
 [146.  28.  77.  97.]
 [150.  34.  78.  90.]
 [152.  39.  78.  88.]
 [156.  27.  78.  89.]
 [162.  29.  79.  83.]
 [164.  31.  81.  93.]
 [168.  33.  86.  95.]
 [174.  36.  87.  92.]
 [176.  30.  88.  86.]
 [180.  35.  93.  90.]
 [182.  32.  97.  86.]
 [184.  29.  98.  88.]
 [186.  30.  99.  97.]
 [190.  36. 103.  85.]
 [194.  38. 113.  91.]
 [200.  30. 137.  83.]]


## Q-2) Customer trend analysis needs age segmented customer data. Fetch the rows corresponding to the age between 20 to 24 (i.e. 20, 21, 22, 23, and 24). 

In [69]:
#Printing all ages of customers
age = cust_data[:,1] # slicing the age column 
print(age)

[19. 21. 20. 23. 31. 22. 35. 23. 64. 30. 67. 35. 58. 24. 37. 22. 35. 20.
 52. 35. 35. 25. 46. 31. 54. 29. 45. 35. 40. 23. 60. 21. 53. 18. 49. 21.
 42. 30. 36. 20. 65. 24. 48. 31. 49. 24. 50. 27. 29. 31. 49. 33. 31. 59.
 50. 47. 51. 69. 27. 53. 70. 19. 67. 54. 63. 18. 43. 68. 19. 32. 70. 47.
 60. 60. 59. 26. 45. 40. 23. 49. 57. 38. 67. 46. 21. 48. 55. 22. 34. 50.
 68. 18. 48. 40. 32. 24. 47. 27. 48. 20. 23. 49. 67. 26. 49. 21. 66. 54.
 68. 66. 65. 19. 38. 19. 18. 19. 63. 49. 51. 50. 27. 38. 40. 39. 23. 31.
 43. 40. 59. 38. 47. 39. 25. 31. 20. 29. 44. 32. 19. 35. 57. 32. 28. 32.
 25. 28. 48. 32. 34. 34. 43. 39. 44. 38. 47. 27. 37. 30. 34. 30. 56. 29.
 19. 31. 50. 36. 42. 33. 36. 32. 40. 28. 36. 36. 52. 30. 58. 27. 59. 35.
 37. 32. 46. 29. 41. 30. 54. 28. 41. 36. 34. 32. 33. 38. 47. 35. 45. 32.
 32. 30.]


In [70]:
#Printing all the ages lies from 20 to 24
INDX = np.where((age >= 20) & (age < 25))
print(age[INDX])

[21. 20. 23. 22. 23. 24. 22. 20. 23. 21. 21. 20. 24. 24. 23. 21. 22. 24.
 20. 23. 21. 23. 20.]


In [71]:
print("Total number of employees who age lies between 20 to 25 is :", age[INDX].size)

Total number of employees who age lies between 20 to 25 is : 23


In [72]:
INDX

(array([  1,   2,   3,   5,   7,  13,  15,  17,  29,  31,  35,  39,  41,
         45,  78,  84,  87,  95,  99, 100, 105, 124, 134], dtype=int64),)

In [73]:
#Displaying the rows pertaining to only the customer age between 21 and 25
print(cust_data[INDX])

[[  2.  21.  15.  81.]
 [  3.  20.  16.   6.]
 [  4.  23.  16.  77.]
 [  6.  22.  17.  76.]
 [  8.  23.  18.  94.]
 [ 14.  24.  20.  77.]
 [ 16.  22.  20.  79.]
 [ 18.  20.  21.  66.]
 [ 30.  23.  29.  87.]
 [ 32.  21.  30.  73.]
 [ 36.  21.  33.  81.]
 [ 40.  20.  37.  75.]
 [ 42.  24.  38.  92.]
 [ 46.  24.  39.  65.]
 [ 79.  23.  54.  52.]
 [ 85.  21.  54.  57.]
 [ 88.  22.  57.  55.]
 [ 96.  24.  60.  52.]
 [100.  20.  61.  49.]
 [101.  23.  62.  41.]
 [106.  21.  62.  42.]
 [125.  23.  70.  29.]
 [135.  20.  73.   5.]]


## Q-3) The company wants to know the customer ID of those who have the lowest annual and highest annual incomes so that they can get an idea of the range of their customer incomes.

In [74]:
Sal = cust_data[:,2] # Slicing the salary column 
print("The lowest annual salary present in dataset is: ",Sal.min())

The lowest annual salary present in dataset is:  15.0


In [75]:
#Finding the index position of customer who's salary is 15 k
INDEX = np.where(Sal == 15)
print(INDEX)

(array([0, 1], dtype=int64),)


In [76]:
#Print customer ID who's annual salary is lowest
CustID = cust_data[:,0]
print("Customer ID of customer who has the lowest salary : ",CustID[INDEX])

Customer ID of customer who has the lowest salary :  [1. 2.]


In [77]:
#Finding the highest salary
Sal = cust_data[:,2] 
print("The highest annual salary present in dataset is: ",Sal.max())

The highest annual salary present in dataset is:  137.0


In [78]:
#Finding the index position of customer who's salary is 137K USD 
INDEX1 = np.where(Sal == 137)
print(INDEX1)

(array([198, 199], dtype=int64),)


In [79]:
#Print customer ID with highest annual salary
CustID = cust_data[:,0]
print("customer ID with highest annual income : ",CustID[INDEX1])

customer ID with highest annual income :  [199. 200.]


In [80]:
#Finding the average annual salary of customer
print("The average annual income of all customers : ",np.mean(cust_data[:,2]))

The average annual income of all customers :  60.56


## Q-4) The marketing team wants the details of the customers whose spending score is more than 75 with a minimum annual salary of at least 35K and age is less than 45 years. How many such customers are there in the given data? These identified customers would be eligible for a discount.

In [81]:
IndX = np.where((Spnd > 75) & (age < 45) & (Sal > 35)) 
# Each of the above are individual arrays i.e Spnd, age and Sal which is sliced from original array ! 
print("Index position of customers as per the given condition: \n", IndX)

Index position of customers as per the given condition: 
 (array([ 41, 123, 125, 127, 135, 141, 143, 145, 149, 151, 153, 155, 157,
       161, 163, 167, 173, 175, 179, 181, 183, 185, 189, 193, 195, 199],
      dtype=int64),)


In [82]:
print("Total number of customers who are eligible for discount: ", age[IndX].size)

Total number of customers who are eligible for discount:  26


In [83]:
#Displaying records of all such customers who are eligible for discount
print(cust_data[IndX])

[[ 42.  24.  38.  92.]
 [124.  39.  69.  91.]
 [126.  31.  70.  77.]
 [128.  40.  71.  95.]
 [136.  29.  73.  88.]
 [142.  32.  75.  93.]
 [144.  32.  76.  87.]
 [146.  28.  77.  97.]
 [150.  34.  78.  90.]
 [152.  39.  78.  88.]
 [154.  38.  78.  76.]
 [156.  27.  78.  89.]
 [158.  30.  78.  78.]
 [162.  29.  79.  83.]
 [164.  31.  81.  93.]
 [168.  33.  86.  95.]
 [174.  36.  87.  92.]
 [176.  30.  88.  86.]
 [180.  35.  93.  90.]
 [182.  32.  97.  86.]
 [184.  29.  98.  88.]
 [186.  30.  99.  97.]
 [190.  36. 103.  85.]
 [194.  38. 113.  91.]
 [196.  35. 120.  79.]
 [200.  30. 137.  83.]]


## Q-5) During the Christmas season, the company wants to offer random discount coupons between 10% to 50% to all the customers in the database. A new column about the discount details needs to be maintained along with the original data.

In [87]:
#Generating random discount between 10 to 50 percent for 200 customers in the data 
disc = np.random.randint(10,50, size=(200,1))
disc


array([[48],
       [10],
       [39],
       [43],
       [15],
       [37],
       [14],
       [15],
       [42],
       [30],
       [13],
       [37],
       [47],
       [44],
       [27],
       [29],
       [20],
       [24],
       [15],
       [42],
       [27],
       [14],
       [37],
       [22],
       [13],
       [42],
       [33],
       [19],
       [30],
       [17],
       [24],
       [19],
       [47],
       [31],
       [46],
       [36],
       [21],
       [30],
       [30],
       [29],
       [23],
       [39],
       [41],
       [22],
       [24],
       [32],
       [20],
       [20],
       [48],
       [12],
       [23],
       [29],
       [30],
       [10],
       [47],
       [39],
       [16],
       [15],
       [24],
       [16],
       [40],
       [42],
       [15],
       [46],
       [26],
       [12],
       [10],
       [27],
       [42],
       [16],
       [32],
       [32],
       [45],
       [16],
       [43],
       [10],
       [40],

In [85]:
#Adding the discount data column in existing records of customers

cust_data1 = np.concatenate((cust_data, disc), axis=1)
print(cust_data1)
#You can also write the code as "np.hstack((cust_data, disc))""

[[  1.  19.  15.  39.  41.]
 [  2.  21.  15.  81.  40.]
 [  3.  20.  16.   6.  16.]
 [  4.  23.  16.  77.  41.]
 [  5.  31.  17.  40.  14.]
 [  6.  22.  17.  76.  29.]
 [  7.  35.  18.   6.  39.]
 [  8.  23.  18.  94.  24.]
 [  9.  64.  19.   3.  15.]
 [ 10.  30.  19.  72.  18.]
 [ 11.  67.  19.  14.  20.]
 [ 12.  35.  19.  99.  47.]
 [ 13.  58.  20.  15.  12.]
 [ 14.  24.  20.  77.  35.]
 [ 15.  37.  20.  13.  46.]
 [ 16.  22.  20.  79.  28.]
 [ 17.  35.  21.  35.  46.]
 [ 18.  20.  21.  66.  32.]
 [ 19.  52.  23.  29.  29.]
 [ 20.  35.  23.  98.  47.]
 [ 21.  35.  24.  35.  39.]
 [ 22.  25.  24.  73.  17.]
 [ 23.  46.  25.   5.  11.]
 [ 24.  31.  25.  73.  23.]
 [ 25.  54.  28.  14.  41.]
 [ 26.  29.  28.  82.  47.]
 [ 27.  45.  28.  32.  16.]
 [ 28.  35.  28.  61.  39.]
 [ 29.  40.  29.  31.  10.]
 [ 30.  23.  29.  87.  44.]
 [ 31.  60.  30.   4.  34.]
 [ 32.  21.  30.  73.  48.]
 [ 33.  53.  33.   4.  28.]
 [ 34.  18.  33.  92.  30.]
 [ 35.  49.  33.  14.  48.]
 [ 36.  21.  33.  81

array([[  1.,  19.,  15.,  39.,  15.],
       [  2.,  21.,  15.,  81.,  48.],
       [  3.,  20.,  16.,   6.,  33.],
       [  4.,  23.,  16.,  77.,  21.],
       [  5.,  31.,  17.,  40.,  15.],
       [  6.,  22.,  17.,  76.,  10.],
       [  7.,  35.,  18.,   6.,  11.],
       [  8.,  23.,  18.,  94.,  20.],
       [  9.,  64.,  19.,   3.,  37.],
       [ 10.,  30.,  19.,  72.,  26.],
       [ 11.,  67.,  19.,  14.,  40.],
       [ 12.,  35.,  19.,  99.,  42.],
       [ 13.,  58.,  20.,  15.,  40.],
       [ 14.,  24.,  20.,  77.,  42.],
       [ 15.,  37.,  20.,  13.,  45.],
       [ 16.,  22.,  20.,  79.,  15.],
       [ 17.,  35.,  21.,  35.,  37.],
       [ 18.,  20.,  21.,  66.,  25.],
       [ 19.,  52.,  23.,  29.,  25.],
       [ 20.,  35.,  23.,  98.,  43.],
       [ 21.,  35.,  24.,  35.,  39.],
       [ 22.,  25.,  24.,  73.,  15.],
       [ 23.,  46.,  25.,   5.,  42.],
       [ 24.,  31.,  25.,  73.,  48.],
       [ 25.,  54.,  28.,  14.,  40.],
       [ 26.,  29.,  28.,

## Q-6) Identify those customers who get more than 45% discount.

In [89]:
discount = cust_data1[:,4] # Slicing the discount column 
INDEX2 = np.where(discount > 45) # Identifying the index locations satisfying the condition 
print(INDEX2)

(array([ 11,  14,  16,  19,  25,  31,  34,  43,  48,  54,  57,  59,  67,
        75,  77,  83,  92, 110, 133, 142, 150, 151, 163, 167, 185, 188],
      dtype=int64),)


In [90]:
cust_data1[INDEX2]

array([[ 12.,  35.,  19.,  99.,  47.],
       [ 15.,  37.,  20.,  13.,  46.],
       [ 17.,  35.,  21.,  35.,  46.],
       [ 20.,  35.,  23.,  98.,  47.],
       [ 26.,  29.,  28.,  82.,  47.],
       [ 32.,  21.,  30.,  73.,  48.],
       [ 35.,  49.,  33.,  14.,  48.],
       [ 44.,  31.,  39.,  61.,  49.],
       [ 49.,  29.,  40.,  42.,  48.],
       [ 55.,  50.,  43.,  45.,  46.],
       [ 58.,  69.,  44.,  46.,  47.],
       [ 60.,  53.,  46.,  46.,  49.],
       [ 68.,  68.,  48.,  48.,  49.],
       [ 76.,  26.,  54.,  54.,  48.],
       [ 78.,  40.,  54.,  48.,  46.],
       [ 84.,  46.,  54.,  44.,  48.],
       [ 93.,  48.,  60.,  49.,  47.],
       [111.,  65.,  63.,  52.,  47.],
       [134.,  31.,  72.,  71.,  47.],
       [143.,  28.,  76.,  40.,  48.],
       [151.,  43.,  78.,  17.,  48.],
       [152.,  39.,  78.,  88.,  48.],
       [164.,  31.,  81.,  93.,  49.],
       [168.,  33.,  86.,  95.,  48.],
       [186.,  30.,  99.,  97.,  46.],
       [189.,  41., 103.,