In [4]:
import numpy as np

# TASK 1

In [2]:
hr = np.arange(1,501)
fin = np.arange(501,1001)
it = np.arange(1001,1501)
sales = np.arange(1501,2001)

print(hr)
print(fin)
print(it)
print(sales)

[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107 108
 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125 126
 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143 144
 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161 162
 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179 180
 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197 198
 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215 216
 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233 234
 235 236 237 238 239 240 241 242 243 244 245 246 24

# TASK 2

In [3]:
#1
ctc_hr = np.random.randint(25000,50000,500)
print(ctc_hr)
print(ctc_hr.size)

[33020 47268 47009 33964 42521 43312 35870 38214 40055 32396 49085 43233
 28996 26253 32431 33632 26166 38436 39095 49481 32190 42633 26419 42407
 30255 25156 32101 42014 38792 31728 28254 41555 39493 25042 27777 30348
 49840 29154 47769 44632 29281 29818 47972 39893 47923 46518 44275 30749
 49791 45818 38337 44034 36637 41060 42571 35731 32329 43747 28904 41072
 47092 41862 29357 34888 36619 25846 43902 25381 25627 46335 49405 28791
 29150 41983 43931 31431 29813 47498 49094 28142 30628 26682 37910 40266
 37684 45636 37822 48667 29354 36369 48581 42594 32586 32112 32532 35839
 31349 44749 25910 34745 43052 35129 29565 36630 49946 49272 25285 38983
 48076 25846 39467 38465 49306 32069 45060 47846 37812 33112 26519 25911
 27590 49061 42270 41689 36565 35306 38137 25127 48610 44627 28024 38164
 29908 38730 37722 39287 33336 41384 39569 41366 38216 45712 37314 27045
 43618 34094 36932 33876 25257 27872 45684 26630 28051 44837 30329 49830
 28688 32748 40071 32772 49088 40261 26502 31826 35

In [4]:
#2
ctc_fin = ctc_hr*1.25
print(ctc_fin)

[41275.   59085.   58761.25 42455.   53151.25 54140.   44837.5  47767.5
 50068.75 40495.   61356.25 54041.25 36245.   32816.25 40538.75 42040.
 32707.5  48045.   48868.75 61851.25 40237.5  53291.25 33023.75 53008.75
 37818.75 31445.   40126.25 52517.5  48490.   39660.   35317.5  51943.75
 49366.25 31302.5  34721.25 37935.   62300.   36442.5  59711.25 55790.
 36601.25 37272.5  59965.   49866.25 59903.75 58147.5  55343.75 38436.25
 62238.75 57272.5  47921.25 55042.5  45796.25 51325.   53213.75 44663.75
 40411.25 54683.75 36130.   51340.   58865.   52327.5  36696.25 43610.
 45773.75 32307.5  54877.5  31726.25 32033.75 57918.75 61756.25 35988.75
 36437.5  52478.75 54913.75 39288.75 37266.25 59372.5  61367.5  35177.5
 38285.   33352.5  47387.5  50332.5  47105.   57045.   47277.5  60833.75
 36692.5  45461.25 60726.25 53242.5  40732.5  40140.   40665.   44798.75
 39186.25 55936.25 32387.5  43431.25 53815.   43911.25 36956.25 45787.5
 62432.5  61590.   31606.25 48728.75 60095.   32307.5  49333

In [5]:
#3
ctc_it = ctc_fin/2
print(ctc_it)

[20637.5   29542.5   29380.625 21227.5   26575.625 27070.    22418.75
 23883.75  25034.375 20247.5   30678.125 27020.625 18122.5   16408.125
 20269.375 21020.    16353.75  24022.5   24434.375 30925.625 20118.75
 26645.625 16511.875 26504.375 18909.375 15722.5   20063.125 26258.75
 24245.    19830.    17658.75  25971.875 24683.125 15651.25  17360.625
 18967.5   31150.    18221.25  29855.625 27895.    18300.625 18636.25
 29982.5   24933.125 29951.875 29073.75  27671.875 19218.125 31119.375
 28636.25  23960.625 27521.25  22898.125 25662.5   26606.875 22331.875
 20205.625 27341.875 18065.    25670.    29432.5   26163.75  18348.125
 21805.    22886.875 16153.75  27438.75  15863.125 16016.875 28959.375
 30878.125 17994.375 18218.75  26239.375 27456.875 19644.375 18633.125
 29686.25  30683.75  17588.75  19142.5   16676.25  23693.75  25166.25
 23552.5   28522.5   23638.75  30416.875 18346.25  22730.625 30363.125
 26621.25  20366.25  20070.    20332.5   22399.375 19593.125 27968.125
 16193.75  

In [6]:
#4
ctc_sales = ctc_hr+5000
print(ctc_sales)

[38020 52268 52009 38964 47521 48312 40870 43214 45055 37396 54085 48233
 33996 31253 37431 38632 31166 43436 44095 54481 37190 47633 31419 47407
 35255 30156 37101 47014 43792 36728 33254 46555 44493 30042 32777 35348
 54840 34154 52769 49632 34281 34818 52972 44893 52923 51518 49275 35749
 54791 50818 43337 49034 41637 46060 47571 40731 37329 48747 33904 46072
 52092 46862 34357 39888 41619 30846 48902 30381 30627 51335 54405 33791
 34150 46983 48931 36431 34813 52498 54094 33142 35628 31682 42910 45266
 42684 50636 42822 53667 34354 41369 53581 47594 37586 37112 37532 40839
 36349 49749 30910 39745 48052 40129 34565 41630 54946 54272 30285 43983
 53076 30846 44467 43465 54306 37069 50060 52846 42812 38112 31519 30911
 32590 54061 47270 46689 41565 40306 43137 30127 53610 49627 33024 43164
 34908 43730 42722 44287 38336 46384 44569 46366 43216 50712 42314 32045
 48618 39094 41932 38876 30257 32872 50684 31630 33051 49837 35329 54830
 33688 37748 45071 37772 54088 45261 31502 36826 40

# TASK 3

In [7]:
avg_hr_sal = np.mean(ctc_hr)
print(avg_hr_sal)

avg_fin_sal = np.mean(ctc_fin)
print(avg_fin_sal)

avg_it_sal = np.mean(ctc_it)
print(avg_it_sal)

avg_sales_sal = np.mean(ctc_sales)
print(avg_sales_sal)

#so the finance department is costing more to the company regarding salary.

37293.942
46617.4275
23308.71375
42293.942


# TASK 4

In [8]:
h_hr = np.sort(ctc_hr[::-1])

print("top 10 salaries in hr dep is : \n",h_hr[0:10])

print("sum of highest hr department salaries : \n",np.sum(h_hr))

top 10 salaries in hr dep is : 
 [25030 25035 25042 25127 25156 25203 25208 25257 25285 25327]
sum of highest hr department salaries : 
 18646971


In [9]:

h_fin = np.sort(ctc_fin[::-1])

print("top 10 salaries in fin dep is : \n",h_fin[0:10])

print("sum of highest finance department salaries :\n",np.sum(h_fin))

top 10 salaries in fin dep is : 
 [31287.5  31293.75 31302.5  31408.75 31445.   31503.75 31510.   31571.25
 31606.25 31658.75]
sum of highest finance department salaries :
 23308713.75


In [10]:
h_it = np.sort(ctc_it[::-1])

print("top 10 salaries in it dep is : \n",h_it[0:10])

print("sum of highest it department salaries :\n",np.sum(h_it))

top 10 salaries in it dep is : 
 [15643.75  15646.875 15651.25  15704.375 15722.5   15751.875 15755.
 15785.625 15803.125 15829.375]
sum of highest it department salaries :
 11654356.875


In [11]:
h_sales = np.sort(ctc_sales[::-1])

print("top TEN salaries in sales dep is : \n",h_sales[:10])

print("sum of highest sales department salaries :\n",np.sum(h_sales))

top TEN salaries in sales dep is : 
 [30030 30035 30042 30127 30156 30203 30208 30257 30285 30327]
sum of highest sales department salaries :
 21146971


# TASK 5

In [12]:
ctc_hr1 = np.count_nonzero(ctc_hr[ctc_hr>45000])
print(ctc_hr1)

ctc_fin1 = np.count_nonzero(ctc_fin[ctc_fin>45000])
print(ctc_fin1)

ctc_it1 = np.count_nonzero(ctc_it[ctc_it>45000])
print(ctc_it1)

ctc_sales1 = np.count_nonzero(ctc_sales[ctc_sales>45000])
print(ctc_sales1)


total_employees = ctc_hr1 + ctc_fin1 + ctc_it1 + ctc_sales1
print("sum of total employees :",total_employees)

97
272
0
198
sum of total employees : 567


# TASK 6

In [13]:
upd_sal = np.where(ctc_sales <= 20000,ctc_sales*1.20,ctc_sales)
print(upd_sal)

[38020. 52268. 52009. 38964. 47521. 48312. 40870. 43214. 45055. 37396.
 54085. 48233. 33996. 31253. 37431. 38632. 31166. 43436. 44095. 54481.
 37190. 47633. 31419. 47407. 35255. 30156. 37101. 47014. 43792. 36728.
 33254. 46555. 44493. 30042. 32777. 35348. 54840. 34154. 52769. 49632.
 34281. 34818. 52972. 44893. 52923. 51518. 49275. 35749. 54791. 50818.
 43337. 49034. 41637. 46060. 47571. 40731. 37329. 48747. 33904. 46072.
 52092. 46862. 34357. 39888. 41619. 30846. 48902. 30381. 30627. 51335.
 54405. 33791. 34150. 46983. 48931. 36431. 34813. 52498. 54094. 33142.
 35628. 31682. 42910. 45266. 42684. 50636. 42822. 53667. 34354. 41369.
 53581. 47594. 37586. 37112. 37532. 40839. 36349. 49749. 30910. 39745.
 48052. 40129. 34565. 41630. 54946. 54272. 30285. 43983. 53076. 30846.
 44467. 43465. 54306. 37069. 50060. 52846. 42812. 38112. 31519. 30911.
 32590. 54061. 47270. 46689. 41565. 40306. 43137. 30127. 53610. 49627.
 33024. 43164. 34908. 43730. 42722. 44287. 38336. 46384. 44569. 46366.
 43216

# TASK 7

In [14]:
#print(ctc_sales)

#finding the positions 
post1996 = np.where(sales == 1996)
post1997 = np.where(sales == 1997)
post1998 = np.where(sales == 1998)
post1999 = np.where(sales == 1999)
post2000 = np.where(sales == 2000)

print(post1996)
print(post1997)
print(post1998)
print(post1999)
print(post2000)

#deleting 5 employees
sales = np.delete(sales,(495,496,497,498,499))
print(sales)

(array([495], dtype=int64),)
(array([496], dtype=int64),)
(array([497], dtype=int64),)
(array([498], dtype=int64),)
(array([499], dtype=int64),)
[1501 1502 1503 1504 1505 1506 1507 1508 1509 1510 1511 1512 1513 1514
 1515 1516 1517 1518 1519 1520 1521 1522 1523 1524 1525 1526 1527 1528
 1529 1530 1531 1532 1533 1534 1535 1536 1537 1538 1539 1540 1541 1542
 1543 1544 1545 1546 1547 1548 1549 1550 1551 1552 1553 1554 1555 1556
 1557 1558 1559 1560 1561 1562 1563 1564 1565 1566 1567 1568 1569 1570
 1571 1572 1573 1574 1575 1576 1577 1578 1579 1580 1581 1582 1583 1584
 1585 1586 1587 1588 1589 1590 1591 1592 1593 1594 1595 1596 1597 1598
 1599 1600 1601 1602 1603 1604 1605 1606 1607 1608 1609 1610 1611 1612
 1613 1614 1615 1616 1617 1618 1619 1620 1621 1622 1623 1624 1625 1626
 1627 1628 1629 1630 1631 1632 1633 1634 1635 1636 1637 1638 1639 1640
 1641 1642 1643 1644 1645 1646 1647 1648 1649 1650 1651 1652 1653 1654
 1655 1656 1657 1658 1659 1660 1661 1662 1663 1664 1665 1666 1667 1668
 16

In [15]:
#adding 5 new employees
new_emp = np.arange(2001,2006)
print(new_emp)

[2001 2002 2003 2004 2005]


In [16]:
sales = np.append(sales,new_emp)
print(sales)

[1501 1502 1503 1504 1505 1506 1507 1508 1509 1510 1511 1512 1513 1514
 1515 1516 1517 1518 1519 1520 1521 1522 1523 1524 1525 1526 1527 1528
 1529 1530 1531 1532 1533 1534 1535 1536 1537 1538 1539 1540 1541 1542
 1543 1544 1545 1546 1547 1548 1549 1550 1551 1552 1553 1554 1555 1556
 1557 1558 1559 1560 1561 1562 1563 1564 1565 1566 1567 1568 1569 1570
 1571 1572 1573 1574 1575 1576 1577 1578 1579 1580 1581 1582 1583 1584
 1585 1586 1587 1588 1589 1590 1591 1592 1593 1594 1595 1596 1597 1598
 1599 1600 1601 1602 1603 1604 1605 1606 1607 1608 1609 1610 1611 1612
 1613 1614 1615 1616 1617 1618 1619 1620 1621 1622 1623 1624 1625 1626
 1627 1628 1629 1630 1631 1632 1633 1634 1635 1636 1637 1638 1639 1640
 1641 1642 1643 1644 1645 1646 1647 1648 1649 1650 1651 1652 1653 1654
 1655 1656 1657 1658 1659 1660 1661 1662 1663 1664 1665 1666 1667 1668
 1669 1670 1671 1672 1673 1674 1675 1676 1677 1678 1679 1680 1681 1682
 1683 1684 1685 1686 1687 1688 1689 1690 1691 1692 1693 1694 1695 1696
 1697 

# TASK 8

In [17]:
s_hr = np.sum(hr)
print(s_hr)

s_sales = np.sum(sales)
print(s_sales)

avg_hr = np.mean(ctc_hr)
avg_sales = np.mean(ctc_sales)
diff = avg_sales-avg_hr

print(avg_hr)
print(avg_sales)
print("difference between hr and sales department's salary :",diff)

125250
875275
37293.942
42293.942
difference between hr and sales department's salary : 5000.0


# TASK 9

In [20]:
n = np.count_nonzero(np.where(ctc_sales>50000))
m = np.count_nonzero(np.where(ctc_sales<55000))

print(n)
print(m)
print("employees of more than 50000 and less than 55000 salary in sales department : ",m-n)

97
499
employees of more than 50000 and less than 55000 salary in sales department :  402


# TASK 10

In [2]:
from numpy import genfromtxt

npb = genfromtxt('DS1_C4_S1_Numpy_PracticeBrief.csv',delimiter=',',skip_header=True)
print(npb)
age = npb[:,-1]
npb.shape

[[ 1. 22.]
 [ 2. 27.]
 [ 3. 31.]
 [ 4. 29.]
 [ 5. 27.]
 [ 6. 26.]
 [ 7. 27.]
 [ 8. 23.]
 [ 9. 27.]
 [10. 32.]
 [11. 28.]
 [12. 27.]
 [13. 22.]
 [14. 27.]
 [15. 35.]
 [16. 33.]
 [17. 28.]
 [18. 22.]
 [19. 25.]
 [20. 27.]
 [21. 37.]
 [22. 27.]
 [23. 24.]
 [24. 27.]
 [25. 28.]
 [26. 26.]
 [27. 27.]
 [28. 27.]
 [29. 29.]
 [30. 49.]
 [31. 26.]
 [32. 32.]
 [33. 26.]
 [34. 24.]
 [35. 24.]
 [36. 23.]
 [37. 28.]
 [38. 28.]
 [39. 22.]
 [40. 26.]
 [41. 32.]
 [42. 35.]
 [43. 33.]
 [44. 31.]
 [45. 30.]
 [46. 36.]
 [47. 22.]
 [48. 23.]
 [49. 32.]
 [50. 34.]]


(50, 2)

# TASK 11

In [6]:
print(age)
c = np.where(age>25)
print('people above 25 years are : \n' ,npb[c])

[22. 27. 31. 29. 27. 26. 27. 23. 27. 32. 28. 27. 22. 27. 35. 33. 28. 22.
 25. 27. 37. 27. 24. 27. 28. 26. 27. 27. 29. 49. 26. 32. 26. 24. 24. 23.
 28. 28. 22. 26. 32. 35. 33. 31. 30. 36. 22. 23. 32. 34.]
people above 25 years are : 
 [[ 2. 27.]
 [ 3. 31.]
 [ 4. 29.]
 [ 5. 27.]
 [ 6. 26.]
 [ 7. 27.]
 [ 9. 27.]
 [10. 32.]
 [11. 28.]
 [12. 27.]
 [14. 27.]
 [15. 35.]
 [16. 33.]
 [17. 28.]
 [20. 27.]
 [21. 37.]
 [22. 27.]
 [24. 27.]
 [25. 28.]
 [26. 26.]
 [27. 27.]
 [28. 27.]
 [29. 29.]
 [30. 49.]
 [31. 26.]
 [32. 32.]
 [33. 26.]
 [37. 28.]
 [38. 28.]
 [40. 26.]
 [41. 32.]
 [42. 35.]
 [43. 33.]
 [44. 31.]
 [45. 30.]
 [46. 36.]
 [49. 32.]
 [50. 34.]]


# TASK 12

In [10]:
print(age)

d=np.where((age>30) & (age<35))
print(d)

print("people above 30 and below 35 years are : \n \n" ,npb[d])

[22. 27. 31. 29. 27. 26. 27. 23. 27. 32. 28. 27. 22. 27. 35. 33. 28. 22.
 25. 27. 37. 27. 24. 27. 28. 26. 27. 27. 29. 49. 26. 32. 26. 24. 24. 23.
 28. 28. 22. 26. 32. 35. 33. 31. 30. 36. 22. 23. 32. 34.]
(array([ 2,  9, 15, 31, 40, 42, 43, 48, 49], dtype=int64),)
people above 30 and below 35 years are : 
 
 [[ 3. 31.]
 [10. 32.]
 [16. 33.]
 [32. 32.]
 [41. 32.]
 [43. 33.]
 [44. 31.]
 [49. 32.]
 [50. 34.]]
